// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: resolver/v1/api.proto

package resolverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/docker/secrets-engine/x/api/resolver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ResolverServiceName is the fully-qualified name of the ResolverService service.
	ResolverServiceName = "resolver.v1.ResolverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ResolverServiceGetSecretsProcedure is the fully-qualified name of the ResolverService's
	// GetSecrets RPC.
	ResolverServiceGetSecretsProcedure = "/resolver.v1.ResolverService/GetSecrets"
)

// ResolverServiceClient is a client for the resolver.v1.ResolverService service.
type ResolverServiceClient interface {
	// Resolve a secret by its ID.
	GetSecrets(context.Context, *connect.Request[v1.GetSecretsRequest]) (*connect.Response[v1.GetSecretsResponse], error)
}

// NewResolverServiceClient constructs a client for the resolver.v1.ResolverService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResolverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResolverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resolverServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("ResolverService").Methods()
	return &resolverServiceClient{
		getSecrets: connect.NewClient[v1.GetSecretsRequest, v1.GetSecretsResponse](
			httpClient,
			baseURL+ResolverServiceGetSecretsProcedure,
			connect.WithSchema(resolverServiceMethods.ByName("GetSecrets")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resolverServiceClient implements ResolverServiceClient.
type resolverServiceClient struct {
	getSecrets *connect.Client[v1.GetSecretsRequest, v1.GetSecretsResponse]
}

// GetSecrets calls resolver.v1.ResolverService.GetSecrets.
func (c *resolverServiceClient) GetSecrets(ctx context.Context, req *connect.Request[v1.GetSecretsRequest]) (*connect.Response[v1.GetSecretsResponse], error) {
	return c.getSecrets.CallUnary(ctx, req)
}

// ResolverServiceHandler is an implementation of the resolver.v1.ResolverService service.
type ResolverServiceHandler interface {
	// Resolve a secret by its ID.
	GetSecrets(context.Context, *connect.Request[v1.GetSecretsRequest]) (*connect.Response[v1.GetSecretsResponse], error)
}

// NewResolverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResolverServiceHandler(svc ResolverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resolverServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("ResolverService").Methods()
	resolverServiceGetSecretsHandler := connect.NewUnaryHandler(
		ResolverServiceGetSecretsProcedure,
		svc.GetSecrets,
		connect.WithSchema(resolverServiceMethods.ByName("GetSecrets")),
		connect.WithHandlerOptions(opts...),
	)
	return "/resolver.v1.ResolverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResolverServiceGetSecretsProcedure:
			resolverServiceGetSecretsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResolverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResolverServiceHandler struct{}

func (UnimplementedResolverServiceHandler) GetSecrets(context.Context, *connect.Request[v1.GetSecretsRequest]) (*connect.Response[v1.GetSecretsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resolver.v1.ResolverService.GetSecrets is not implemented"))
}
