// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: resolver/v1/api.proto

package resolverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Version     *string                `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Pattern     *string                `protobuf:"bytes,3,opt,name=pattern"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) GetPattern() string {
	if x != nil {
		if x.xxx_hidden_Pattern != nil {
			return *x.xxx_hidden_Pattern
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterPluginRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterPluginRequest) SetPattern(v string) {
	x.xxx_hidden_Pattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RegisterPluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPluginRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPluginRequest) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RegisterPluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *RegisterPluginRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *RegisterPluginRequest) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Pattern = nil
}

type RegisterPluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the plugin to register.
	Name *string
	// Version of the plugin.
	Version *string
	// Pattern
	Pattern *string
}

func (b0 RegisterPluginRequest_builder) Build() *RegisterPluginRequest {
	m0 := &RegisterPluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Version = b.Version
	}
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_Pattern = b.Pattern
	}
	return m0
}

type RegisterPluginResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EngineName     *string                `protobuf:"bytes,1,opt,name=engine_name,json=engineName"`
	xxx_hidden_EngineVersion  *string                `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion"`
	xxx_hidden_RequestTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=request_timeout,json=requestTimeout"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPluginResponse) GetEngineName() string {
	if x != nil {
		if x.xxx_hidden_EngineName != nil {
			return *x.xxx_hidden_EngineName
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginResponse) GetEngineVersion() string {
	if x != nil {
		if x.xxx_hidden_EngineVersion != nil {
			return *x.xxx_hidden_EngineVersion
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginResponse) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_RequestTimeout
	}
	return nil
}

func (x *RegisterPluginResponse) SetEngineName(v string) {
	x.xxx_hidden_EngineName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterPluginResponse) SetEngineVersion(v string) {
	x.xxx_hidden_EngineVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterPluginResponse) SetRequestTimeout(v *durationpb.Duration) {
	x.xxx_hidden_RequestTimeout = v
}

func (x *RegisterPluginResponse) HasEngineName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPluginResponse) HasEngineVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPluginResponse) HasRequestTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestTimeout != nil
}

func (x *RegisterPluginResponse) ClearEngineName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EngineName = nil
}

func (x *RegisterPluginResponse) ClearEngineVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EngineVersion = nil
}

func (x *RegisterPluginResponse) ClearRequestTimeout() {
	x.xxx_hidden_RequestTimeout = nil
}

type RegisterPluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the runtime engine is running in.
	EngineName *string
	// Version of the runtime engine is running in.
	EngineVersion *string
	// Configured request processing timeout in milliseconds.
	RequestTimeout *durationpb.Duration
}

func (b0 RegisterPluginResponse_builder) Build() *RegisterPluginResponse {
	m0 := &RegisterPluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EngineName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EngineName = b.EngineName
	}
	if b.EngineVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_EngineVersion = b.EngineVersion
	}
	x.xxx_hidden_RequestTimeout = b.RequestTimeout
	return m0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownRequest_builder) Build() *ShutdownRequest {
	m0 := &ShutdownRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownResponse_builder) Build() *ShutdownResponse {
	m0 := &ShutdownResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetSecretsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pattern     *string                `protobuf:"bytes,1,opt,name=pattern"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsRequest) GetPattern() string {
	if x != nil {
		if x.xxx_hidden_Pattern != nil {
			return *x.xxx_hidden_Pattern
		}
		return ""
	}
	return ""
}

func (x *GetSecretsRequest) SetPattern(v string) {
	x.xxx_hidden_Pattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSecretsRequest) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretsRequest) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pattern = nil
}

type GetSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the secret to resolve.
	Pattern *string
}

func (b0 GetSecretsRequest_builder) Build() *GetSecretsRequest {
	m0 := &GetSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pattern = b.Pattern
	}
	return m0
}

type GetSecretsResponse struct {
	state                protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Envelopes *[]*GetSecretsResponse_Envelope `protobuf:"bytes,1,rep,name=envelopes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsResponse) GetEnvelopes() []*GetSecretsResponse_Envelope {
	if x != nil {
		if x.xxx_hidden_Envelopes != nil {
			return *x.xxx_hidden_Envelopes
		}
	}
	return nil
}

func (x *GetSecretsResponse) SetEnvelopes(v []*GetSecretsResponse_Envelope) {
	x.xxx_hidden_Envelopes = &v
}

type GetSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Envelopes []*GetSecretsResponse_Envelope
}

func (b0 GetSecretsResponse_builder) Build() *GetSecretsResponse {
	m0 := &GetSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Envelopes = &b.Envelopes
	return m0
}

type GetCAResponse struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CaCertificate *string                `protobuf:"bytes,1,opt,name=ca_certificate,json=caCertificate"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *GetCAResponse) Reset() {
	*x = GetCAResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCAResponse) ProtoMessage() {}

func (x *GetCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetCAResponse) GetCaCertificate() string {
	if x != nil {
		if x.xxx_hidden_CaCertificate != nil {
			return *x.xxx_hidden_CaCertificate
		}
		return ""
	}
	return ""
}

func (x *GetCAResponse) SetCaCertificate(v string) {
	x.xxx_hidden_CaCertificate = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetCAResponse) HasCaCertificate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetCAResponse) ClearCaCertificate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CaCertificate = nil
}

type GetCAResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CaCertificate *string
}

func (b0 GetCAResponse_builder) Build() *GetCAResponse {
	m0 := &GetCAResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CaCertificate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_CaCertificate = b.CaCertificate
	}
	return m0
}

type SignCertRequest struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CertificateRequest *string                `protobuf:"bytes,1,opt,name=certificate_request,json=certificateRequest"`
	XXX_raceDetectHookData        protoimpl.RaceDetectHookData
	XXX_presence                  [1]uint32
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *SignCertRequest) Reset() {
	*x = SignCertRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertRequest) ProtoMessage() {}

func (x *SignCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignCertRequest) GetCertificateRequest() string {
	if x != nil {
		if x.xxx_hidden_CertificateRequest != nil {
			return *x.xxx_hidden_CertificateRequest
		}
		return ""
	}
	return ""
}

func (x *SignCertRequest) SetCertificateRequest(v string) {
	x.xxx_hidden_CertificateRequest = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SignCertRequest) HasCertificateRequest() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SignCertRequest) ClearCertificateRequest() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CertificateRequest = nil
}

type SignCertRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CertificateRequest *string
}

func (b0 SignCertRequest_builder) Build() *SignCertRequest {
	m0 := &SignCertRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CertificateRequest != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_CertificateRequest = b.CertificateRequest
	}
	return m0
}

type SignCertResponse struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SignedCertificate *string                `protobuf:"bytes,1,opt,name=signed_certificate,json=signedCertificate"`
	XXX_raceDetectHookData       protoimpl.RaceDetectHookData
	XXX_presence                 [1]uint32
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *SignCertResponse) Reset() {
	*x = SignCertResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCertResponse) ProtoMessage() {}

func (x *SignCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SignCertResponse) GetSignedCertificate() string {
	if x != nil {
		if x.xxx_hidden_SignedCertificate != nil {
			return *x.xxx_hidden_SignedCertificate
		}
		return ""
	}
	return ""
}

func (x *SignCertResponse) SetSignedCertificate(v string) {
	x.xxx_hidden_SignedCertificate = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SignCertResponse) HasSignedCertificate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SignCertResponse) ClearSignedCertificate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_SignedCertificate = nil
}

type SignCertResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	SignedCertificate *string
}

func (b0 SignCertResponse_builder) Build() *SignCertResponse {
	m0 := &SignCertResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.SignedCertificate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_SignedCertificate = b.SignedCertificate
	}
	return m0
}

type GetSecretsResponse_Envelope struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       []byte                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Provider    *string                `protobuf:"bytes,3,opt,name=provider"`
	xxx_hidden_Version     *string                `protobuf:"bytes,4,opt,name=version"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_ResolvedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=resolved_at,json=resolvedAt"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretsResponse_Envelope) Reset() {
	*x = GetSecretsResponse_Envelope{}
	mi := &file_resolver_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse_Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse_Envelope) ProtoMessage() {}

func (x *GetSecretsResponse_Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsResponse_Envelope) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetProvider() string {
	if x != nil {
		if x.xxx_hidden_Provider != nil {
			return *x.xxx_hidden_Provider
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ResolvedAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 7)
}

func (x *GetSecretsResponse_Envelope) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 7)
}

func (x *GetSecretsResponse_Envelope) SetProvider(v string) {
	x.xxx_hidden_Provider = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 7)
}

func (x *GetSecretsResponse_Envelope) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 7)
}

func (x *GetSecretsResponse_Envelope) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *GetSecretsResponse_Envelope) SetResolvedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ResolvedAt = v
}

func (x *GetSecretsResponse_Envelope) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *GetSecretsResponse_Envelope) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretsResponse_Envelope) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetSecretsResponse_Envelope) HasProvider() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetSecretsResponse_Envelope) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetSecretsResponse_Envelope) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *GetSecretsResponse_Envelope) HasResolvedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResolvedAt != nil
}

func (x *GetSecretsResponse_Envelope) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *GetSecretsResponse_Envelope) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *GetSecretsResponse_Envelope) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

func (x *GetSecretsResponse_Envelope) ClearProvider() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Provider = nil
}

func (x *GetSecretsResponse_Envelope) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = nil
}

func (x *GetSecretsResponse_Envelope) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *GetSecretsResponse_Envelope) ClearResolvedAt() {
	x.xxx_hidden_ResolvedAt = nil
}

func (x *GetSecretsResponse_Envelope) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type GetSecretsResponse_Envelope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the secret to resolve.
	Id *string
	// The resolved secret value.
	Value      []byte
	Provider   *string
	Version    *string
	CreatedAt  *timestamppb.Timestamp
	ResolvedAt *timestamppb.Timestamp
	ExpiresAt  *timestamppb.Timestamp
}

func (b0 GetSecretsResponse_Envelope_builder) Build() *GetSecretsResponse_Envelope {
	m0 := &GetSecretsResponse_Envelope{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 7)
		x.xxx_hidden_Id = b.Id
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 7)
		x.xxx_hidden_Value = b.Value
	}
	if b.Provider != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 7)
		x.xxx_hidden_Provider = b.Provider
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 7)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_ResolvedAt = b.ResolvedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

var File_resolver_v1_api_proto protoreflect.FileDescriptor

const file_resolver_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x15resolver/v1/api.proto\x12\vresolver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1bgoogle/protobuf/empty.proto\"_\n" +
	"\x15RegisterPluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\apattern\x18\x03 \x01(\tR\apattern\"\xa4\x01\n" +
	"\x16RegisterPluginResponse\x12\x1f\n" +
	"\vengine_name\x18\x01 \x01(\tR\n" +
	"engineName\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12B\n" +
	"\x0frequest_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"-\n" +
	"\x11GetSecretsRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"\xf8\x02\n" +
	"\x12GetSecretsResponse\x12F\n" +
	"\tenvelopes\x18\x01 \x03(\v2(.resolver.v1.GetSecretsResponse.EnvelopeR\tenvelopes\x1a\x99\x02\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vresolved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"6\n" +
	"\rGetCAResponse\x12%\n" +
	"\x0eca_certificate\x18\x01 \x01(\tR\rcaCertificate\"B\n" +
	"\x0fSignCertRequest\x12/\n" +
	"\x13certificate_request\x18\x01 \x01(\tR\x12certificateRequest\"A\n" +
	"\x10SignCertResponse\x12-\n" +
	"\x12signed_certificate\x18\x01 \x01(\tR\x11signedCertificate2j\n" +
	"\rEngineService\x12Y\n" +
	"\x0eRegisterPlugin\x12\".resolver.v1.RegisterPluginRequest\x1a#.resolver.v1.RegisterPluginResponse2X\n" +
	"\rPluginService\x12G\n" +
	"\bShutdown\x12\x1c.resolver.v1.ShutdownRequest\x1a\x1d.resolver.v1.ShutdownResponse2`\n" +
	"\x0fResolverService\x12M\n" +
	"\n" +
	"GetSecrets\x12\x1e.resolver.v1.GetSecretsRequest\x1a\x1f.resolver.v1.GetSecretsResponse2\x98\x01\n" +
	"\vCertService\x12@\n" +
	"\x05GetCA\x12\x16.google.protobuf.Empty\x1a\x1a.resolver.v1.GetCAResponse\"\x03\x90\x02\x01\x12G\n" +
	"\bSignCert\x12\x1c.resolver.v1.SignCertRequest\x1a\x1d.resolver.v1.SignCertResponseB\xa7\x01\n" +
	"\x0fcom.resolver.v1B\bApiProtoP\x01Z=github.com/docker/secrets-engine/x/api/resolver/v1;resolverv1\xa2\x02\x03RXX\xaa\x02\vResolver.V1\xca\x02\vResolver\\V1\xe2\x02\x17Resolver\\V1\\GPBMetadata\xea\x02\fResolver::V1b\beditionsp\xe8\a"

var file_resolver_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_resolver_v1_api_proto_goTypes = []any{
	(*RegisterPluginRequest)(nil),       // 0: resolver.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil),      // 1: resolver.v1.RegisterPluginResponse
	(*ShutdownRequest)(nil),             // 2: resolver.v1.ShutdownRequest
	(*ShutdownResponse)(nil),            // 3: resolver.v1.ShutdownResponse
	(*GetSecretsRequest)(nil),           // 4: resolver.v1.GetSecretsRequest
	(*GetSecretsResponse)(nil),          // 5: resolver.v1.GetSecretsResponse
	(*GetCAResponse)(nil),               // 6: resolver.v1.GetCAResponse
	(*SignCertRequest)(nil),             // 7: resolver.v1.SignCertRequest
	(*SignCertResponse)(nil),            // 8: resolver.v1.SignCertResponse
	(*GetSecretsResponse_Envelope)(nil), // 9: resolver.v1.GetSecretsResponse.Envelope
	(*durationpb.Duration)(nil),         // 10: google.protobuf.Duration
	(*timestamppb.Timestamp)(nil),       // 11: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 12: google.protobuf.Empty
}
var file_resolver_v1_api_proto_depIdxs = []int32{
	10, // 0: resolver.v1.RegisterPluginResponse.request_timeout:type_name -> google.protobuf.Duration
	9,  // 1: resolver.v1.GetSecretsResponse.envelopes:type_name -> resolver.v1.GetSecretsResponse.Envelope
	11, // 2: resolver.v1.GetSecretsResponse.Envelope.created_at:type_name -> google.protobuf.Timestamp
	11, // 3: resolver.v1.GetSecretsResponse.Envelope.resolved_at:type_name -> google.protobuf.Timestamp
	11, // 4: resolver.v1.GetSecretsResponse.Envelope.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 5: resolver.v1.EngineService.RegisterPlugin:input_type -> resolver.v1.RegisterPluginRequest
	2,  // 6: resolver.v1.PluginService.Shutdown:input_type -> resolver.v1.ShutdownRequest
	4,  // 7: resolver.v1.ResolverService.GetSecrets:input_type -> resolver.v1.GetSecretsRequest
	12, // 8: resolver.v1.CertService.GetCA:input_type -> google.protobuf.Empty
	7,  // 9: resolver.v1.CertService.SignCert:input_type -> resolver.v1.SignCertRequest
	1,  // 10: resolver.v1.EngineService.RegisterPlugin:output_type -> resolver.v1.RegisterPluginResponse
	3,  // 11: resolver.v1.PluginService.Shutdown:output_type -> resolver.v1.ShutdownResponse
	5,  // 12: resolver.v1.ResolverService.GetSecrets:output_type -> resolver.v1.GetSecretsResponse
	6,  // 13: resolver.v1.CertService.GetCA:output_type -> resolver.v1.GetCAResponse
	8,  // 14: resolver.v1.CertService.SignCert:output_type -> resolver.v1.SignCertResponse
	10, // [10:15] is the sub-list for method output_type
	5,  // [5:10] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_resolver_v1_api_proto_init() }
func file_resolver_v1_api_proto_init() {
	if File_resolver_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resolver_v1_api_proto_rawDesc), len(file_resolver_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   4,
		},
		GoTypes:           file_resolver_v1_api_proto_goTypes,
		DependencyIndexes: file_resolver_v1_api_proto_depIdxs,
		MessageInfos:      file_resolver_v1_api_proto_msgTypes,
	}.Build()
	File_resolver_v1_api_proto = out.File
	file_resolver_v1_api_proto_goTypes = nil
	file_resolver_v1_api_proto_depIdxs = nil
}
