// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: resolver/v1/api.proto

package resolverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSecretsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pattern     *string                `protobuf:"bytes,1,opt,name=pattern"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretsRequest) Reset() {
	*x = GetSecretsRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsRequest) ProtoMessage() {}

func (x *GetSecretsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsRequest) GetPattern() string {
	if x != nil {
		if x.xxx_hidden_Pattern != nil {
			return *x.xxx_hidden_Pattern
		}
		return ""
	}
	return ""
}

func (x *GetSecretsRequest) SetPattern(v string) {
	x.xxx_hidden_Pattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *GetSecretsRequest) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretsRequest) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pattern = nil
}

type GetSecretsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the secret to resolve.
	Pattern *string
}

func (b0 GetSecretsRequest_builder) Build() *GetSecretsRequest {
	m0 := &GetSecretsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pattern = b.Pattern
	}
	return m0
}

type AuthorizeRequest struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Patterns []string               `protobuf:"bytes,1,rep,name=patterns"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *AuthorizeRequest) Reset() {
	*x = AuthorizeRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeRequest) ProtoMessage() {}

func (x *AuthorizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthorizeRequest) GetPatterns() []string {
	if x != nil {
		return x.xxx_hidden_Patterns
	}
	return nil
}

func (x *AuthorizeRequest) SetPatterns(v []string) {
	x.xxx_hidden_Patterns = v
}

type AuthorizeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Patterns to authorize; at least one required.
	Patterns []string
}

func (b0 AuthorizeRequest_builder) Build() *AuthorizeRequest {
	m0 := &AuthorizeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Patterns = b.Patterns
	return m0
}

type AuthorizeResponse struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ExpiresAt *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=expires_at,json=expiresAt"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AuthorizeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *AuthorizeResponse) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *AuthorizeResponse) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *AuthorizeResponse) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type AuthorizeResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// When the authorization expires.
	ExpiresAt *timestamppb.Timestamp
}

func (b0 AuthorizeResponse_builder) Build() *AuthorizeResponse {
	m0 := &AuthorizeResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	return m0
}

type GetSecretsResponse struct {
	state                protoimpl.MessageState          `protogen:"opaque.v1"`
	xxx_hidden_Envelopes *[]*GetSecretsResponse_Envelope `protobuf:"bytes,1,rep,name=envelopes"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetSecretsResponse) Reset() {
	*x = GetSecretsResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse) ProtoMessage() {}

func (x *GetSecretsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsResponse) GetEnvelopes() []*GetSecretsResponse_Envelope {
	if x != nil {
		if x.xxx_hidden_Envelopes != nil {
			return *x.xxx_hidden_Envelopes
		}
	}
	return nil
}

func (x *GetSecretsResponse) SetEnvelopes(v []*GetSecretsResponse_Envelope) {
	x.xxx_hidden_Envelopes = &v
}

type GetSecretsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Envelopes []*GetSecretsResponse_Envelope
}

func (b0 GetSecretsResponse_builder) Build() *GetSecretsResponse {
	m0 := &GetSecretsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Envelopes = &b.Envelopes
	return m0
}

type GetSecretsResponse_Envelope struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Value       []byte                 `protobuf:"bytes,2,opt,name=value"`
	xxx_hidden_Provider    *string                `protobuf:"bytes,3,opt,name=provider"`
	xxx_hidden_Version     *string                `protobuf:"bytes,4,opt,name=version"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt"`
	xxx_hidden_ResolvedAt  *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=resolved_at,json=resolvedAt"`
	xxx_hidden_ExpiresAt   *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt"`
	xxx_hidden_Metadata    map[string]string      `protobuf:"bytes,8,rep,name=metadata" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetSecretsResponse_Envelope) Reset() {
	*x = GetSecretsResponse_Envelope{}
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSecretsResponse_Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSecretsResponse_Envelope) ProtoMessage() {}

func (x *GetSecretsResponse_Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetSecretsResponse_Envelope) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetValue() []byte {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetProvider() string {
	if x != nil {
		if x.xxx_hidden_Provider != nil {
			return *x.xxx_hidden_Provider
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GetSecretsResponse_Envelope) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ResolvedAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) GetMetadata() map[string]string {
	if x != nil {
		return x.xxx_hidden_Metadata
	}
	return nil
}

func (x *GetSecretsResponse_Envelope) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *GetSecretsResponse_Envelope) SetValue(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Value = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *GetSecretsResponse_Envelope) SetProvider(v string) {
	x.xxx_hidden_Provider = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *GetSecretsResponse_Envelope) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *GetSecretsResponse_Envelope) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *GetSecretsResponse_Envelope) SetResolvedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ResolvedAt = v
}

func (x *GetSecretsResponse_Envelope) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *GetSecretsResponse_Envelope) SetMetadata(v map[string]string) {
	x.xxx_hidden_Metadata = v
}

func (x *GetSecretsResponse_Envelope) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetSecretsResponse_Envelope) HasValue() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetSecretsResponse_Envelope) HasProvider() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetSecretsResponse_Envelope) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *GetSecretsResponse_Envelope) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *GetSecretsResponse_Envelope) HasResolvedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ResolvedAt != nil
}

func (x *GetSecretsResponse_Envelope) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *GetSecretsResponse_Envelope) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *GetSecretsResponse_Envelope) ClearValue() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Value = nil
}

func (x *GetSecretsResponse_Envelope) ClearProvider() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Provider = nil
}

func (x *GetSecretsResponse_Envelope) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Version = nil
}

func (x *GetSecretsResponse_Envelope) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *GetSecretsResponse_Envelope) ClearResolvedAt() {
	x.xxx_hidden_ResolvedAt = nil
}

func (x *GetSecretsResponse_Envelope) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

type GetSecretsResponse_Envelope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// ID of the secret to resolve.
	Id *string
	// The resolved secret value.
	Value      []byte
	Provider   *string
	Version    *string
	CreatedAt  *timestamppb.Timestamp
	ResolvedAt *timestamppb.Timestamp
	ExpiresAt  *timestamppb.Timestamp
	Metadata   map[string]string
}

func (b0 GetSecretsResponse_Envelope_builder) Build() *GetSecretsResponse_Envelope {
	m0 := &GetSecretsResponse_Envelope{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Id = b.Id
	}
	if b.Value != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Value = b.Value
	}
	if b.Provider != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Provider = b.Provider
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_Version = b.Version
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_ResolvedAt = b.ResolvedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_Metadata = b.Metadata
	return m0
}

var File_resolver_v1_api_proto protoreflect.FileDescriptor

const file_resolver_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x15resolver/v1/api.proto\x12\vresolver.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"-\n" +
	"\x11GetSecretsRequest\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\".\n" +
	"\x10AuthorizeRequest\x12\x1a\n" +
	"\bpatterns\x18\x01 \x03(\tR\bpatterns\"N\n" +
	"\x11AuthorizeResponse\x129\n" +
	"\n" +
	"expires_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"\x89\x04\n" +
	"\x12GetSecretsResponse\x12F\n" +
	"\tenvelopes\x18\x01 \x03(\v2(.resolver.v1.GetSecretsResponse.EnvelopeR\tenvelopes\x1a\xaa\x03\n" +
	"\bEnvelope\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\x12\x1a\n" +
	"\bprovider\x18\x03 \x01(\tR\bprovider\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12;\n" +
	"\vresolved_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"resolvedAt\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12R\n" +
	"\bmetadata\x18\b \x03(\v26.resolver.v1.GetSecretsResponse.Envelope.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x012`\n" +
	"\x0fResolverService\x12M\n" +
	"\n" +
	"GetSecrets\x12\x1e.resolver.v1.GetSecretsRequest\x1a\x1f.resolver.v1.GetSecretsResponse2_\n" +
	"\x11AuthorizerService\x12J\n" +
	"\tAuthorize\x12\x1d.resolver.v1.AuthorizeRequest\x1a\x1e.resolver.v1.AuthorizeResponseB\xa7\x01\n" +
	"\x0fcom.resolver.v1B\bApiProtoP\x01Z=github.com/docker/secrets-engine/x/api/resolver/v1;resolverv1\xa2\x02\x03RXX\xaa\x02\vResolver.V1\xca\x02\vResolver\\V1\xe2\x02\x17Resolver\\V1\\GPBMetadata\xea\x02\fResolver::V1b\beditionsp\xe8\a"

var file_resolver_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resolver_v1_api_proto_goTypes = []any{
	(*GetSecretsRequest)(nil),           // 0: resolver.v1.GetSecretsRequest
	(*AuthorizeRequest)(nil),            // 1: resolver.v1.AuthorizeRequest
	(*AuthorizeResponse)(nil),           // 2: resolver.v1.AuthorizeResponse
	(*GetSecretsResponse)(nil),          // 3: resolver.v1.GetSecretsResponse
	(*GetSecretsResponse_Envelope)(nil), // 4: resolver.v1.GetSecretsResponse.Envelope
	nil,                                 // 5: resolver.v1.GetSecretsResponse.Envelope.MetadataEntry
	(*timestamppb.Timestamp)(nil),       // 6: google.protobuf.Timestamp
}
var file_resolver_v1_api_proto_depIdxs = []int32{
	6, // 0: resolver.v1.AuthorizeResponse.expires_at:type_name -> google.protobuf.Timestamp
	4, // 1: resolver.v1.GetSecretsResponse.envelopes:type_name -> resolver.v1.GetSecretsResponse.Envelope
	6, // 2: resolver.v1.GetSecretsResponse.Envelope.created_at:type_name -> google.protobuf.Timestamp
	6, // 3: resolver.v1.GetSecretsResponse.Envelope.resolved_at:type_name -> google.protobuf.Timestamp
	6, // 4: resolver.v1.GetSecretsResponse.Envelope.expires_at:type_name -> google.protobuf.Timestamp
	5, // 5: resolver.v1.GetSecretsResponse.Envelope.metadata:type_name -> resolver.v1.GetSecretsResponse.Envelope.MetadataEntry
	0, // 6: resolver.v1.ResolverService.GetSecrets:input_type -> resolver.v1.GetSecretsRequest
	1, // 7: resolver.v1.AuthorizerService.Authorize:input_type -> resolver.v1.AuthorizeRequest
	3, // 8: resolver.v1.ResolverService.GetSecrets:output_type -> resolver.v1.GetSecretsResponse
	2, // 9: resolver.v1.AuthorizerService.Authorize:output_type -> resolver.v1.AuthorizeResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_resolver_v1_api_proto_init() }
func file_resolver_v1_api_proto_init() {
	if File_resolver_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resolver_v1_api_proto_rawDesc), len(file_resolver_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_resolver_v1_api_proto_goTypes,
		DependencyIndexes: file_resolver_v1_api_proto_depIdxs,
		MessageInfos:      file_resolver_v1_api_proto_msgTypes,
	}.Build()
	File_resolver_v1_api_proto = out.File
	file_resolver_v1_api_proto_goTypes = nil
	file_resolver_v1_api_proto_depIdxs = nil
}
