// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: plugins/v1/api.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Plugin struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name         *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Version      *string                `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Disabled     bool                   `protobuf:"varint,3,opt,name=disabled"`
	xxx_hidden_External     bool                   `protobuf:"varint,4,opt,name=external"`
	xxx_hidden_Configurable bool                   `protobuf:"varint,5,opt,name=configurable"`
	xxx_hidden_Metadata     isPlugin_Metadata      `protobuf_oneof:"metadata"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_plugins_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Plugin) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Plugin) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Plugin) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *Plugin) GetExternal() bool {
	if x != nil {
		return x.xxx_hidden_External
	}
	return false
}

func (x *Plugin) GetConfigurable() bool {
	if x != nil {
		return x.xxx_hidden_Configurable
	}
	return false
}

func (x *Plugin) GetSecretsProvider() *SecretsProvider {
	if x != nil {
		if x, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider); ok {
			return x.SecretsProvider
		}
	}
	return nil
}

func (x *Plugin) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 6)
}

func (x *Plugin) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 6)
}

func (x *Plugin) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 6)
}

func (x *Plugin) SetExternal(v bool) {
	x.xxx_hidden_External = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 6)
}

func (x *Plugin) SetConfigurable(v bool) {
	x.xxx_hidden_Configurable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Plugin) SetSecretsProvider(v *SecretsProvider) {
	if v == nil {
		x.xxx_hidden_Metadata = nil
		return
	}
	x.xxx_hidden_Metadata = &plugin_SecretsProvider{v}
}

func (x *Plugin) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Plugin) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Plugin) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Plugin) HasExternal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Plugin) HasConfigurable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Plugin) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Plugin) HasSecretsProvider() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider)
	return ok
}

func (x *Plugin) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Plugin) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *Plugin) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Disabled = false
}

func (x *Plugin) ClearExternal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_External = false
}

func (x *Plugin) ClearConfigurable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Configurable = false
}

func (x *Plugin) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Plugin) ClearSecretsProvider() {
	if _, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider); ok {
		x.xxx_hidden_Metadata = nil
	}
}

const Plugin_Metadata_not_set_case case_Plugin_Metadata = 0
const Plugin_SecretsProvider_case case_Plugin_Metadata = 6

func (x *Plugin) WhichMetadata() case_Plugin_Metadata {
	if x == nil {
		return Plugin_Metadata_not_set_case
	}
	switch x.xxx_hidden_Metadata.(type) {
	case *plugin_SecretsProvider:
		return Plugin_SecretsProvider_case
	default:
		return Plugin_Metadata_not_set_case
	}
}

type Plugin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name
	Name *string
	// Version
	Version *string
	// Enabled vs disabled
	Disabled *bool
	// External vs builtin
	External *bool
	// Configurable
	Configurable *bool
	// Type-specific fields

	// Fields of oneof xxx_hidden_Metadata:
	SecretsProvider *SecretsProvider
	// -- end of xxx_hidden_Metadata
}

func (b0 Plugin_builder) Build() *Plugin {
	m0 := &Plugin{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 6)
		x.xxx_hidden_Name = b.Name
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 6)
		x.xxx_hidden_Version = b.Version
	}
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 6)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	if b.External != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 6)
		x.xxx_hidden_External = *b.External
	}
	if b.Configurable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_Configurable = *b.Configurable
	}
	if b.SecretsProvider != nil {
		x.xxx_hidden_Metadata = &plugin_SecretsProvider{b.SecretsProvider}
	}
	return m0
}

type case_Plugin_Metadata protoreflect.FieldNumber

func (x case_Plugin_Metadata) String() string {
	md := file_plugins_v1_api_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlugin_Metadata interface {
	isPlugin_Metadata()
}

type plugin_SecretsProvider struct {
	SecretsProvider *SecretsProvider `protobuf:"bytes,6,opt,name=secrets_provider,json=secretsProvider,oneof"`
}

func (*plugin_SecretsProvider) isPlugin_Metadata() {}

type SecretsProvider struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pattern     *string                `protobuf:"bytes,1,opt,name=pattern"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretsProvider) Reset() {
	*x = SecretsProvider{}
	mi := &file_plugins_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsProvider) ProtoMessage() {}

func (x *SecretsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretsProvider) GetPattern() string {
	if x != nil {
		if x.xxx_hidden_Pattern != nil {
			return *x.xxx_hidden_Pattern
		}
		return ""
	}
	return ""
}

func (x *SecretsProvider) SetPattern(v string) {
	x.xxx_hidden_Pattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SecretsProvider) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretsProvider) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pattern = nil
}

type SecretsProvider_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pattern
	Pattern *string
}

func (b0 SecretsProvider_builder) Build() *SecretsProvider {
	m0 := &SecretsProvider{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pattern = b.Pattern
	}
	return m0
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListPluginsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListPluginsRequest_builder) Build() *ListPluginsRequest {
	m0 := &ListPluginsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListPluginsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Plugins *[]*Plugin             `protobuf:"bytes,1,rep,name=plugins"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListPluginsResponse) GetPlugins() []*Plugin {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *ListPluginsResponse) SetPlugins(v []*Plugin) {
	x.xxx_hidden_Plugins = &v
}

type ListPluginsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plugins []*Plugin
}

func (b0 ListPluginsResponse_builder) Build() *ListPluginsResponse {
	m0 := &ListPluginsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plugins = &b.Plugins
	return m0
}

type EnablePluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EnablePluginRequest) Reset() {
	*x = EnablePluginRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginRequest) ProtoMessage() {}

func (x *EnablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnablePluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *EnablePluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EnablePluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EnablePluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type EnablePluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 EnablePluginRequest_builder) Build() *EnablePluginRequest {
	m0 := &EnablePluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type EnablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginResponse) Reset() {
	*x = EnablePluginResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginResponse) ProtoMessage() {}

func (x *EnablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EnablePluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EnablePluginResponse_builder) Build() *EnablePluginResponse {
	m0 := &EnablePluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DisablePluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DisablePluginRequest) Reset() {
	*x = DisablePluginRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginRequest) ProtoMessage() {}

func (x *DisablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisablePluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DisablePluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DisablePluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DisablePluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type DisablePluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 DisablePluginRequest_builder) Build() *DisablePluginRequest {
	m0 := &DisablePluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type DisablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePluginResponse) Reset() {
	*x = DisablePluginResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginResponse) ProtoMessage() {}

func (x *DisablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisablePluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisablePluginResponse_builder) Build() *DisablePluginResponse {
	m0 := &DisablePluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_plugins_v1_api_proto protoreflect.FileDescriptor

const file_plugins_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x14plugins/v1/api.proto\x12\n" +
	"plugins.v1\"\xe8\x01\n" +
	"\x06Plugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bexternal\x18\x04 \x01(\bR\bexternal\x12\"\n" +
	"\fconfigurable\x18\x05 \x01(\bR\fconfigurable\x12H\n" +
	"\x10secrets_provider\x18\x06 \x01(\v2\x1b.plugins.v1.SecretsProviderH\x00R\x0fsecretsProviderB\n" +
	"\n" +
	"\bmetadata\"+\n" +
	"\x0fSecretsProvider\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"\x14\n" +
	"\x12ListPluginsRequest\"C\n" +
	"\x13ListPluginsResponse\x12,\n" +
	"\aplugins\x18\x01 \x03(\v2\x12.plugins.v1.PluginR\aplugins\")\n" +
	"\x13EnablePluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14EnablePluginResponse\"*\n" +
	"\x14DisablePluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DisablePluginResponse2\x92\x02\n" +
	"\x17PluginManagementService\x12N\n" +
	"\vListPlugins\x12\x1e.plugins.v1.ListPluginsRequest\x1a\x1f.plugins.v1.ListPluginsResponse\x12Q\n" +
	"\fEnablePlugin\x12\x1f.plugins.v1.EnablePluginRequest\x1a .plugins.v1.EnablePluginResponse\x12T\n" +
	"\rDisablePlugin\x12 .plugins.v1.DisablePluginRequest\x1a!.plugins.v1.DisablePluginResponseB\xa0\x01\n" +
	"\x0ecom.plugins.v1B\bApiProtoP\x01Z;github.com/docker/secrets-engine/x/api/plugins/v1;pluginsv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Plugins.V1\xca\x02\n" +
	"Plugins\\V1\xe2\x02\x16Plugins\\V1\\GPBMetadata\xea\x02\vPlugins::V1b\beditionsp\xe8\a"

var file_plugins_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_plugins_v1_api_proto_goTypes = []any{
	(*Plugin)(nil),                // 0: plugins.v1.Plugin
	(*SecretsProvider)(nil),       // 1: plugins.v1.SecretsProvider
	(*ListPluginsRequest)(nil),    // 2: plugins.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),   // 3: plugins.v1.ListPluginsResponse
	(*EnablePluginRequest)(nil),   // 4: plugins.v1.EnablePluginRequest
	(*EnablePluginResponse)(nil),  // 5: plugins.v1.EnablePluginResponse
	(*DisablePluginRequest)(nil),  // 6: plugins.v1.DisablePluginRequest
	(*DisablePluginResponse)(nil), // 7: plugins.v1.DisablePluginResponse
}
var file_plugins_v1_api_proto_depIdxs = []int32{
	1, // 0: plugins.v1.Plugin.secrets_provider:type_name -> plugins.v1.SecretsProvider
	0, // 1: plugins.v1.ListPluginsResponse.plugins:type_name -> plugins.v1.Plugin
	2, // 2: plugins.v1.PluginManagementService.ListPlugins:input_type -> plugins.v1.ListPluginsRequest
	4, // 3: plugins.v1.PluginManagementService.EnablePlugin:input_type -> plugins.v1.EnablePluginRequest
	6, // 4: plugins.v1.PluginManagementService.DisablePlugin:input_type -> plugins.v1.DisablePluginRequest
	3, // 5: plugins.v1.PluginManagementService.ListPlugins:output_type -> plugins.v1.ListPluginsResponse
	5, // 6: plugins.v1.PluginManagementService.EnablePlugin:output_type -> plugins.v1.EnablePluginResponse
	7, // 7: plugins.v1.PluginManagementService.DisablePlugin:output_type -> plugins.v1.DisablePluginResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_plugins_v1_api_proto_init() }
func file_plugins_v1_api_proto_init() {
	if File_plugins_v1_api_proto != nil {
		return
	}
	file_plugins_v1_api_proto_msgTypes[0].OneofWrappers = []any{
		(*plugin_SecretsProvider)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_v1_api_proto_rawDesc), len(file_plugins_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugins_v1_api_proto_goTypes,
		DependencyIndexes: file_plugins_v1_api_proto_depIdxs,
		MessageInfos:      file_plugins_v1_api_proto_msgTypes,
	}.Build()
	File_plugins_v1_api_proto = out.File
	file_plugins_v1_api_proto_goTypes = nil
	file_plugins_v1_api_proto_depIdxs = nil
}
