// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: plugins/v1/api.proto

package pluginsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunStatus int32

const (
	RunStatus_RUN_STATUS_UNSPECIFIED      RunStatus = 0
	RunStatus_RUN_STATUS_RUNNING          RunStatus = 1
	RunStatus_RUN_STATUS_STOPPED          RunStatus = 2
	RunStatus_RUN_STATUS_CRASHED          RunStatus = 3
	RunStatus_RUN_STATUS_RETRIES_EXCEEDED RunStatus = 4
)

// Enum value maps for RunStatus.
var (
	RunStatus_name = map[int32]string{
		0: "RUN_STATUS_UNSPECIFIED",
		1: "RUN_STATUS_RUNNING",
		2: "RUN_STATUS_STOPPED",
		3: "RUN_STATUS_CRASHED",
		4: "RUN_STATUS_RETRIES_EXCEEDED",
	}
	RunStatus_value = map[string]int32{
		"RUN_STATUS_UNSPECIFIED":      0,
		"RUN_STATUS_RUNNING":          1,
		"RUN_STATUS_STOPPED":          2,
		"RUN_STATUS_CRASHED":          3,
		"RUN_STATUS_RETRIES_EXCEEDED": 4,
	}
)

func (x RunStatus) Enum() *RunStatus {
	p := new(RunStatus)
	*p = x
	return p
}

func (x RunStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RunStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_plugins_v1_api_proto_enumTypes[0].Descriptor()
}

func (RunStatus) Type() protoreflect.EnumType {
	return &file_plugins_v1_api_proto_enumTypes[0]
}

func (x RunStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type RegisterPluginRequest struct {
	state                  protoimpl.MessageState           `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                          `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Version     *string                          `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Metadata    isRegisterPluginRequest_Metadata `protobuf_oneof:"metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) GetSecretsProvider() *SecretsProvider {
	if x != nil {
		if x, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_SecretsProvider); ok {
			return x.SecretsProvider
		}
	}
	return nil
}

func (x *RegisterPluginRequest) GetAccessControlModule() *AccessControlModule {
	if x != nil {
		if x, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_AccessControlModule); ok {
			return x.AccessControlModule
		}
	}
	return nil
}

func (x *RegisterPluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterPluginRequest) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterPluginRequest) SetSecretsProvider(v *SecretsProvider) {
	if v == nil {
		x.xxx_hidden_Metadata = nil
		return
	}
	x.xxx_hidden_Metadata = &registerPluginRequest_SecretsProvider{v}
}

func (x *RegisterPluginRequest) SetAccessControlModule(v *AccessControlModule) {
	if v == nil {
		x.xxx_hidden_Metadata = nil
		return
	}
	x.xxx_hidden_Metadata = &registerPluginRequest_AccessControlModule{v}
}

func (x *RegisterPluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPluginRequest) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPluginRequest) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *RegisterPluginRequest) HasSecretsProvider() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_SecretsProvider)
	return ok
}

func (x *RegisterPluginRequest) HasAccessControlModule() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_AccessControlModule)
	return ok
}

func (x *RegisterPluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *RegisterPluginRequest) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *RegisterPluginRequest) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *RegisterPluginRequest) ClearSecretsProvider() {
	if _, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_SecretsProvider); ok {
		x.xxx_hidden_Metadata = nil
	}
}

func (x *RegisterPluginRequest) ClearAccessControlModule() {
	if _, ok := x.xxx_hidden_Metadata.(*registerPluginRequest_AccessControlModule); ok {
		x.xxx_hidden_Metadata = nil
	}
}

const RegisterPluginRequest_Metadata_not_set_case case_RegisterPluginRequest_Metadata = 0
const RegisterPluginRequest_SecretsProvider_case case_RegisterPluginRequest_Metadata = 3
const RegisterPluginRequest_AccessControlModule_case case_RegisterPluginRequest_Metadata = 4

func (x *RegisterPluginRequest) WhichMetadata() case_RegisterPluginRequest_Metadata {
	if x == nil {
		return RegisterPluginRequest_Metadata_not_set_case
	}
	switch x.xxx_hidden_Metadata.(type) {
	case *registerPluginRequest_SecretsProvider:
		return RegisterPluginRequest_SecretsProvider_case
	case *registerPluginRequest_AccessControlModule:
		return RegisterPluginRequest_AccessControlModule_case
	default:
		return RegisterPluginRequest_Metadata_not_set_case
	}
}

type RegisterPluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the plugin to register.
	Name *string
	// Version of the plugin.
	Version *string
	// Type-specific fields

	// Fields of oneof xxx_hidden_Metadata:
	SecretsProvider     *SecretsProvider
	AccessControlModule *AccessControlModule
	// -- end of xxx_hidden_Metadata
}

func (b0 RegisterPluginRequest_builder) Build() *RegisterPluginRequest {
	m0 := &RegisterPluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Name = b.Name
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Version = b.Version
	}
	if b.SecretsProvider != nil {
		x.xxx_hidden_Metadata = &registerPluginRequest_SecretsProvider{b.SecretsProvider}
	}
	if b.AccessControlModule != nil {
		x.xxx_hidden_Metadata = &registerPluginRequest_AccessControlModule{b.AccessControlModule}
	}
	return m0
}

type case_RegisterPluginRequest_Metadata protoreflect.FieldNumber

func (x case_RegisterPluginRequest_Metadata) String() string {
	md := file_plugins_v1_api_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isRegisterPluginRequest_Metadata interface {
	isRegisterPluginRequest_Metadata()
}

type registerPluginRequest_SecretsProvider struct {
	SecretsProvider *SecretsProvider `protobuf:"bytes,3,opt,name=secrets_provider,json=secretsProvider,oneof"`
}

type registerPluginRequest_AccessControlModule struct {
	AccessControlModule *AccessControlModule `protobuf:"bytes,4,opt,name=access_control_module,json=accessControlModule,oneof"`
}

func (*registerPluginRequest_SecretsProvider) isRegisterPluginRequest_Metadata() {}

func (*registerPluginRequest_AccessControlModule) isRegisterPluginRequest_Metadata() {}

type RegisterPluginResponse struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_EngineName     *string                `protobuf:"bytes,1,opt,name=engine_name,json=engineName"`
	xxx_hidden_EngineVersion  *string                `protobuf:"bytes,2,opt,name=engine_version,json=engineVersion"`
	xxx_hidden_RequestTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=request_timeout,json=requestTimeout"`
	XXX_raceDetectHookData    protoimpl.RaceDetectHookData
	XXX_presence              [1]uint32
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPluginResponse) GetEngineName() string {
	if x != nil {
		if x.xxx_hidden_EngineName != nil {
			return *x.xxx_hidden_EngineName
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginResponse) GetEngineVersion() string {
	if x != nil {
		if x.xxx_hidden_EngineVersion != nil {
			return *x.xxx_hidden_EngineVersion
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginResponse) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_RequestTimeout
	}
	return nil
}

func (x *RegisterPluginResponse) SetEngineName(v string) {
	x.xxx_hidden_EngineName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RegisterPluginResponse) SetEngineVersion(v string) {
	x.xxx_hidden_EngineVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RegisterPluginResponse) SetRequestTimeout(v *durationpb.Duration) {
	x.xxx_hidden_RequestTimeout = v
}

func (x *RegisterPluginResponse) HasEngineName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPluginResponse) HasEngineVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPluginResponse) HasRequestTimeout() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_RequestTimeout != nil
}

func (x *RegisterPluginResponse) ClearEngineName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_EngineName = nil
}

func (x *RegisterPluginResponse) ClearEngineVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EngineVersion = nil
}

func (x *RegisterPluginResponse) ClearRequestTimeout() {
	x.xxx_hidden_RequestTimeout = nil
}

type RegisterPluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the secrets engine is running in.
	EngineName *string
	// Version of the runtime engine is running in.
	EngineVersion *string
	// Configured request processing timeout in milliseconds.
	RequestTimeout *durationpb.Duration
}

func (b0 RegisterPluginResponse_builder) Build() *RegisterPluginResponse {
	m0 := &RegisterPluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.EngineName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_EngineName = b.EngineName
	}
	if b.EngineVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_EngineVersion = b.EngineVersion
	}
	x.xxx_hidden_RequestTimeout = b.RequestTimeout
	return m0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownRequest_builder) Build() *ShutdownRequest {
	m0 := &ShutdownRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownResponse_builder) Build() *ShutdownResponse {
	m0 := &ShutdownResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Plugin struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name          *string                `protobuf:"bytes,1,opt,name=name"`
	xxx_hidden_Version       *string                `protobuf:"bytes,2,opt,name=version"`
	xxx_hidden_Disabled      bool                   `protobuf:"varint,3,opt,name=disabled"`
	xxx_hidden_External      bool                   `protobuf:"varint,4,opt,name=external"`
	xxx_hidden_Configurable  bool                   `protobuf:"varint,5,opt,name=configurable"`
	xxx_hidden_RunStatus     RunStatus              `protobuf:"varint,6,opt,name=run_status,json=runStatus,enum=plugins.v1.RunStatus"`
	xxx_hidden_StatusMessage *string                `protobuf:"bytes,7,opt,name=status_message,json=statusMessage"`
	xxx_hidden_Metadata      isPlugin_Metadata      `protobuf_oneof:"metadata"`
	XXX_raceDetectHookData   protoimpl.RaceDetectHookData
	XXX_presence             [1]uint32
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Plugin) Reset() {
	*x = Plugin{}
	mi := &file_plugins_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Plugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Plugin) ProtoMessage() {}

func (x *Plugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Plugin) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *Plugin) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *Plugin) GetDisabled() bool {
	if x != nil {
		return x.xxx_hidden_Disabled
	}
	return false
}

func (x *Plugin) GetExternal() bool {
	if x != nil {
		return x.xxx_hidden_External
	}
	return false
}

func (x *Plugin) GetConfigurable() bool {
	if x != nil {
		return x.xxx_hidden_Configurable
	}
	return false
}

func (x *Plugin) GetRunStatus() RunStatus {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 5) {
			return x.xxx_hidden_RunStatus
		}
	}
	return RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *Plugin) GetStatusMessage() string {
	if x != nil {
		if x.xxx_hidden_StatusMessage != nil {
			return *x.xxx_hidden_StatusMessage
		}
		return ""
	}
	return ""
}

func (x *Plugin) GetSecretsProvider() *SecretsProvider {
	if x != nil {
		if x, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider); ok {
			return x.SecretsProvider
		}
	}
	return nil
}

func (x *Plugin) GetAccessControlModule() *AccessControlModule {
	if x != nil {
		if x, ok := x.xxx_hidden_Metadata.(*plugin_AccessControlModule); ok {
			return x.AccessControlModule
		}
	}
	return nil
}

func (x *Plugin) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 8)
}

func (x *Plugin) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 8)
}

func (x *Plugin) SetDisabled(v bool) {
	x.xxx_hidden_Disabled = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 8)
}

func (x *Plugin) SetExternal(v bool) {
	x.xxx_hidden_External = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 8)
}

func (x *Plugin) SetConfigurable(v bool) {
	x.xxx_hidden_Configurable = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 8)
}

func (x *Plugin) SetRunStatus(v RunStatus) {
	x.xxx_hidden_RunStatus = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 8)
}

func (x *Plugin) SetStatusMessage(v string) {
	x.xxx_hidden_StatusMessage = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 8)
}

func (x *Plugin) SetSecretsProvider(v *SecretsProvider) {
	if v == nil {
		x.xxx_hidden_Metadata = nil
		return
	}
	x.xxx_hidden_Metadata = &plugin_SecretsProvider{v}
}

func (x *Plugin) SetAccessControlModule(v *AccessControlModule) {
	if v == nil {
		x.xxx_hidden_Metadata = nil
		return
	}
	x.xxx_hidden_Metadata = &plugin_AccessControlModule{v}
}

func (x *Plugin) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Plugin) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Plugin) HasDisabled() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Plugin) HasExternal() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Plugin) HasConfigurable() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Plugin) HasRunStatus() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Plugin) HasStatusMessage() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *Plugin) HasMetadata() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Metadata != nil
}

func (x *Plugin) HasSecretsProvider() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider)
	return ok
}

func (x *Plugin) HasAccessControlModule() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Metadata.(*plugin_AccessControlModule)
	return ok
}

func (x *Plugin) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

func (x *Plugin) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Version = nil
}

func (x *Plugin) ClearDisabled() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Disabled = false
}

func (x *Plugin) ClearExternal() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_External = false
}

func (x *Plugin) ClearConfigurable() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Configurable = false
}

func (x *Plugin) ClearRunStatus() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_RunStatus = RunStatus_RUN_STATUS_UNSPECIFIED
}

func (x *Plugin) ClearStatusMessage() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_StatusMessage = nil
}

func (x *Plugin) ClearMetadata() {
	x.xxx_hidden_Metadata = nil
}

func (x *Plugin) ClearSecretsProvider() {
	if _, ok := x.xxx_hidden_Metadata.(*plugin_SecretsProvider); ok {
		x.xxx_hidden_Metadata = nil
	}
}

func (x *Plugin) ClearAccessControlModule() {
	if _, ok := x.xxx_hidden_Metadata.(*plugin_AccessControlModule); ok {
		x.xxx_hidden_Metadata = nil
	}
}

const Plugin_Metadata_not_set_case case_Plugin_Metadata = 0
const Plugin_SecretsProvider_case case_Plugin_Metadata = 8
const Plugin_AccessControlModule_case case_Plugin_Metadata = 9

func (x *Plugin) WhichMetadata() case_Plugin_Metadata {
	if x == nil {
		return Plugin_Metadata_not_set_case
	}
	switch x.xxx_hidden_Metadata.(type) {
	case *plugin_SecretsProvider:
		return Plugin_SecretsProvider_case
	case *plugin_AccessControlModule:
		return Plugin_AccessControlModule_case
	default:
		return Plugin_Metadata_not_set_case
	}
}

type Plugin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name
	Name *string
	// Version
	Version *string
	// Enabled vs disabled
	Disabled *bool
	// External vs builtin
	External *bool
	// Configurable
	Configurable *bool
	// Run status
	RunStatus *RunStatus
	// Human-readable detail for the current run_status. Populated for
	// terminal/error statuses (CRASHED, RETRIES_EXCEEDED); typically empty
	// otherwise. Not machine-parseable — intended for display only.
	StatusMessage *string
	// Type-specific fields

	// Fields of oneof xxx_hidden_Metadata:
	SecretsProvider     *SecretsProvider
	AccessControlModule *AccessControlModule
	// -- end of xxx_hidden_Metadata
}

func (b0 Plugin_builder) Build() *Plugin {
	m0 := &Plugin{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 8)
		x.xxx_hidden_Name = b.Name
	}
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 8)
		x.xxx_hidden_Version = b.Version
	}
	if b.Disabled != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 8)
		x.xxx_hidden_Disabled = *b.Disabled
	}
	if b.External != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 8)
		x.xxx_hidden_External = *b.External
	}
	if b.Configurable != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 8)
		x.xxx_hidden_Configurable = *b.Configurable
	}
	if b.RunStatus != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 8)
		x.xxx_hidden_RunStatus = *b.RunStatus
	}
	if b.StatusMessage != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 8)
		x.xxx_hidden_StatusMessage = b.StatusMessage
	}
	if b.SecretsProvider != nil {
		x.xxx_hidden_Metadata = &plugin_SecretsProvider{b.SecretsProvider}
	}
	if b.AccessControlModule != nil {
		x.xxx_hidden_Metadata = &plugin_AccessControlModule{b.AccessControlModule}
	}
	return m0
}

type case_Plugin_Metadata protoreflect.FieldNumber

func (x case_Plugin_Metadata) String() string {
	md := file_plugins_v1_api_proto_msgTypes[4].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isPlugin_Metadata interface {
	isPlugin_Metadata()
}

type plugin_SecretsProvider struct {
	SecretsProvider *SecretsProvider `protobuf:"bytes,8,opt,name=secrets_provider,json=secretsProvider,oneof"`
}

type plugin_AccessControlModule struct {
	AccessControlModule *AccessControlModule `protobuf:"bytes,9,opt,name=access_control_module,json=accessControlModule,oneof"`
}

func (*plugin_SecretsProvider) isPlugin_Metadata() {}

func (*plugin_AccessControlModule) isPlugin_Metadata() {}

type SecretsProvider struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Pattern     *string                `protobuf:"bytes,1,opt,name=pattern"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *SecretsProvider) Reset() {
	*x = SecretsProvider{}
	mi := &file_plugins_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SecretsProvider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SecretsProvider) ProtoMessage() {}

func (x *SecretsProvider) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *SecretsProvider) GetPattern() string {
	if x != nil {
		if x.xxx_hidden_Pattern != nil {
			return *x.xxx_hidden_Pattern
		}
		return ""
	}
	return ""
}

func (x *SecretsProvider) SetPattern(v string) {
	x.xxx_hidden_Pattern = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *SecretsProvider) HasPattern() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *SecretsProvider) ClearPattern() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Pattern = nil
}

type SecretsProvider_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Pattern
	Pattern *string
}

func (b0 SecretsProvider_builder) Build() *SecretsProvider {
	m0 := &SecretsProvider{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Pattern != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Pattern = b.Pattern
	}
	return m0
}

type AccessControlModule struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessControlModule) Reset() {
	*x = AccessControlModule{}
	mi := &file_plugins_v1_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControlModule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControlModule) ProtoMessage() {}

func (x *AccessControlModule) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type AccessControlModule_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 AccessControlModule_builder) Build() *AccessControlModule {
	m0 := &AccessControlModule{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListPluginsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListPluginsRequest_builder) Build() *ListPluginsRequest {
	m0 := &ListPluginsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ListPluginsResponse struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Plugins *[]*Plugin             `protobuf:"bytes,1,rep,name=plugins"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListPluginsResponse) GetPlugins() []*Plugin {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *ListPluginsResponse) SetPlugins(v []*Plugin) {
	x.xxx_hidden_Plugins = &v
}

type ListPluginsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plugins []*Plugin
}

func (b0 ListPluginsResponse_builder) Build() *ListPluginsResponse {
	m0 := &ListPluginsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plugins = &b.Plugins
	return m0
}

type EnablePluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EnablePluginRequest) Reset() {
	*x = EnablePluginRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginRequest) ProtoMessage() {}

func (x *EnablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EnablePluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *EnablePluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *EnablePluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EnablePluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type EnablePluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 EnablePluginRequest_builder) Build() *EnablePluginRequest {
	m0 := &EnablePluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type EnablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnablePluginResponse) Reset() {
	*x = EnablePluginResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnablePluginResponse) ProtoMessage() {}

func (x *EnablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type EnablePluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 EnablePluginResponse_builder) Build() *EnablePluginResponse {
	m0 := &EnablePluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type DisablePluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name        *string                `protobuf:"bytes,1,opt,name=name"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *DisablePluginRequest) Reset() {
	*x = DisablePluginRequest{}
	mi := &file_plugins_v1_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginRequest) ProtoMessage() {}

func (x *DisablePluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DisablePluginRequest) GetName() string {
	if x != nil {
		if x.xxx_hidden_Name != nil {
			return *x.xxx_hidden_Name
		}
		return ""
	}
	return ""
}

func (x *DisablePluginRequest) SetName(v string) {
	x.xxx_hidden_Name = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *DisablePluginRequest) HasName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *DisablePluginRequest) ClearName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Name = nil
}

type DisablePluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name *string
}

func (b0 DisablePluginRequest_builder) Build() *DisablePluginRequest {
	m0 := &DisablePluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Name != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Name = b.Name
	}
	return m0
}

type DisablePluginResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePluginResponse) Reset() {
	*x = DisablePluginResponse{}
	mi := &file_plugins_v1_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePluginResponse) ProtoMessage() {}

func (x *DisablePluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugins_v1_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type DisablePluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 DisablePluginResponse_builder) Build() *DisablePluginResponse {
	m0 := &DisablePluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_plugins_v1_api_proto protoreflect.FileDescriptor

const file_plugins_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x14plugins/v1/api.proto\x12\n" +
	"plugins.v1\x1a\x1egoogle/protobuf/duration.proto\"\xf2\x01\n" +
	"\x15RegisterPluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12H\n" +
	"\x10secrets_provider\x18\x03 \x01(\v2\x1b.plugins.v1.SecretsProviderH\x00R\x0fsecretsProvider\x12U\n" +
	"\x15access_control_module\x18\x04 \x01(\v2\x1f.plugins.v1.AccessControlModuleH\x00R\x13accessControlModuleB\n" +
	"\n" +
	"\bmetadata\"\xa4\x01\n" +
	"\x16RegisterPluginResponse\x12\x1f\n" +
	"\vengine_name\x18\x01 \x01(\tR\n" +
	"engineName\x12%\n" +
	"\x0eengine_version\x18\x02 \x01(\tR\rengineVersion\x12B\n" +
	"\x0frequest_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse\"\x9c\x03\n" +
	"\x06Plugin\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x1a\n" +
	"\bdisabled\x18\x03 \x01(\bR\bdisabled\x12\x1a\n" +
	"\bexternal\x18\x04 \x01(\bR\bexternal\x12\"\n" +
	"\fconfigurable\x18\x05 \x01(\bR\fconfigurable\x124\n" +
	"\n" +
	"run_status\x18\x06 \x01(\x0e2\x15.plugins.v1.RunStatusR\trunStatus\x12%\n" +
	"\x0estatus_message\x18\a \x01(\tR\rstatusMessage\x12H\n" +
	"\x10secrets_provider\x18\b \x01(\v2\x1b.plugins.v1.SecretsProviderH\x00R\x0fsecretsProvider\x12U\n" +
	"\x15access_control_module\x18\t \x01(\v2\x1f.plugins.v1.AccessControlModuleH\x00R\x13accessControlModuleB\n" +
	"\n" +
	"\bmetadata\"+\n" +
	"\x0fSecretsProvider\x12\x18\n" +
	"\apattern\x18\x01 \x01(\tR\apattern\"\x15\n" +
	"\x13AccessControlModule\"\x14\n" +
	"\x12ListPluginsRequest\"C\n" +
	"\x13ListPluginsResponse\x12,\n" +
	"\aplugins\x18\x01 \x03(\v2\x12.plugins.v1.PluginR\aplugins\")\n" +
	"\x13EnablePluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x16\n" +
	"\x14EnablePluginResponse\"*\n" +
	"\x14DisablePluginRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x17\n" +
	"\x15DisablePluginResponse*\x90\x01\n" +
	"\tRunStatus\x12\x1a\n" +
	"\x16RUN_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12RUN_STATUS_RUNNING\x10\x01\x12\x16\n" +
	"\x12RUN_STATUS_STOPPED\x10\x02\x12\x16\n" +
	"\x12RUN_STATUS_CRASHED\x10\x03\x12\x1f\n" +
	"\x1bRUN_STATUS_RETRIES_EXCEEDED\x10\x042j\n" +
	"\x0fRegisterService\x12W\n" +
	"\x0eRegisterPlugin\x12!.plugins.v1.RegisterPluginRequest\x1a\".plugins.v1.RegisterPluginResponse2V\n" +
	"\rPluginService\x12E\n" +
	"\bShutdown\x12\x1b.plugins.v1.ShutdownRequest\x1a\x1c.plugins.v1.ShutdownResponse2\x92\x02\n" +
	"\x17PluginManagementService\x12N\n" +
	"\vListPlugins\x12\x1e.plugins.v1.ListPluginsRequest\x1a\x1f.plugins.v1.ListPluginsResponse\x12Q\n" +
	"\fEnablePlugin\x12\x1f.plugins.v1.EnablePluginRequest\x1a .plugins.v1.EnablePluginResponse\x12T\n" +
	"\rDisablePlugin\x12 .plugins.v1.DisablePluginRequest\x1a!.plugins.v1.DisablePluginResponseB\xa0\x01\n" +
	"\x0ecom.plugins.v1B\bApiProtoP\x01Z;github.com/docker/secrets-engine/x/api/plugins/v1;pluginsv1\xa2\x02\x03PXX\xaa\x02\n" +
	"Plugins.V1\xca\x02\n" +
	"Plugins\\V1\xe2\x02\x16Plugins\\V1\\GPBMetadata\xea\x02\vPlugins::V1b\beditionsp\xe8\a"

var file_plugins_v1_api_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugins_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_plugins_v1_api_proto_goTypes = []any{
	(RunStatus)(0),                 // 0: plugins.v1.RunStatus
	(*RegisterPluginRequest)(nil),  // 1: plugins.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil), // 2: plugins.v1.RegisterPluginResponse
	(*ShutdownRequest)(nil),        // 3: plugins.v1.ShutdownRequest
	(*ShutdownResponse)(nil),       // 4: plugins.v1.ShutdownResponse
	(*Plugin)(nil),                 // 5: plugins.v1.Plugin
	(*SecretsProvider)(nil),        // 6: plugins.v1.SecretsProvider
	(*AccessControlModule)(nil),    // 7: plugins.v1.AccessControlModule
	(*ListPluginsRequest)(nil),     // 8: plugins.v1.ListPluginsRequest
	(*ListPluginsResponse)(nil),    // 9: plugins.v1.ListPluginsResponse
	(*EnablePluginRequest)(nil),    // 10: plugins.v1.EnablePluginRequest
	(*EnablePluginResponse)(nil),   // 11: plugins.v1.EnablePluginResponse
	(*DisablePluginRequest)(nil),   // 12: plugins.v1.DisablePluginRequest
	(*DisablePluginResponse)(nil),  // 13: plugins.v1.DisablePluginResponse
	(*durationpb.Duration)(nil),    // 14: google.protobuf.Duration
}
var file_plugins_v1_api_proto_depIdxs = []int32{
	6,  // 0: plugins.v1.RegisterPluginRequest.secrets_provider:type_name -> plugins.v1.SecretsProvider
	7,  // 1: plugins.v1.RegisterPluginRequest.access_control_module:type_name -> plugins.v1.AccessControlModule
	14, // 2: plugins.v1.RegisterPluginResponse.request_timeout:type_name -> google.protobuf.Duration
	0,  // 3: plugins.v1.Plugin.run_status:type_name -> plugins.v1.RunStatus
	6,  // 4: plugins.v1.Plugin.secrets_provider:type_name -> plugins.v1.SecretsProvider
	7,  // 5: plugins.v1.Plugin.access_control_module:type_name -> plugins.v1.AccessControlModule
	5,  // 6: plugins.v1.ListPluginsResponse.plugins:type_name -> plugins.v1.Plugin
	1,  // 7: plugins.v1.RegisterService.RegisterPlugin:input_type -> plugins.v1.RegisterPluginRequest
	3,  // 8: plugins.v1.PluginService.Shutdown:input_type -> plugins.v1.ShutdownRequest
	8,  // 9: plugins.v1.PluginManagementService.ListPlugins:input_type -> plugins.v1.ListPluginsRequest
	10, // 10: plugins.v1.PluginManagementService.EnablePlugin:input_type -> plugins.v1.EnablePluginRequest
	12, // 11: plugins.v1.PluginManagementService.DisablePlugin:input_type -> plugins.v1.DisablePluginRequest
	2,  // 12: plugins.v1.RegisterService.RegisterPlugin:output_type -> plugins.v1.RegisterPluginResponse
	4,  // 13: plugins.v1.PluginService.Shutdown:output_type -> plugins.v1.ShutdownResponse
	9,  // 14: plugins.v1.PluginManagementService.ListPlugins:output_type -> plugins.v1.ListPluginsResponse
	11, // 15: plugins.v1.PluginManagementService.EnablePlugin:output_type -> plugins.v1.EnablePluginResponse
	13, // 16: plugins.v1.PluginManagementService.DisablePlugin:output_type -> plugins.v1.DisablePluginResponse
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_plugins_v1_api_proto_init() }
func file_plugins_v1_api_proto_init() {
	if File_plugins_v1_api_proto != nil {
		return
	}
	file_plugins_v1_api_proto_msgTypes[0].OneofWrappers = []any{
		(*registerPluginRequest_SecretsProvider)(nil),
		(*registerPluginRequest_AccessControlModule)(nil),
	}
	file_plugins_v1_api_proto_msgTypes[4].OneofWrappers = []any{
		(*plugin_SecretsProvider)(nil),
		(*plugin_AccessControlModule)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugins_v1_api_proto_rawDesc), len(file_plugins_v1_api_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_plugins_v1_api_proto_goTypes,
		DependencyIndexes: file_plugins_v1_api_proto_depIdxs,
		EnumInfos:         file_plugins_v1_api_proto_enumTypes,
		MessageInfos:      file_plugins_v1_api_proto_msgTypes,
	}.Build()
	File_plugins_v1_api_proto = out.File
	file_plugins_v1_api_proto_goTypes = nil
	file_plugins_v1_api_proto_depIdxs = nil
}
