// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: accesscontrol/v1/api.proto

package accesscontrolv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/docker/secrets-engine/x/api/accesscontrol/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// AccessControlServiceName is the fully-qualified name of the AccessControlService service.
	AccessControlServiceName = "accesscontrol.v1.AccessControlService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// AccessControlServiceCheckAccessProcedure is the fully-qualified name of the
	// AccessControlService's CheckAccess RPC.
	AccessControlServiceCheckAccessProcedure = "/accesscontrol.v1.AccessControlService/CheckAccess"
)

// AccessControlServiceClient is a client for the accesscontrol.v1.AccessControlService service.
type AccessControlServiceClient interface {
	// CheckAccess decides whether a requesting process may resolve the
	// secrets matched by the query. Called for every GetSecrets request.
	CheckAccess(context.Context, *connect.Request[v1.CheckAccessRequest]) (*connect.Response[v1.CheckAccessResponse], error)
}

// NewAccessControlServiceClient constructs a client for the accesscontrol.v1.AccessControlService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewAccessControlServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) AccessControlServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	accessControlServiceMethods := v1.File_accesscontrol_v1_api_proto.Services().ByName("AccessControlService").Methods()
	return &accessControlServiceClient{
		checkAccess: connect.NewClient[v1.CheckAccessRequest, v1.CheckAccessResponse](
			httpClient,
			baseURL+AccessControlServiceCheckAccessProcedure,
			connect.WithSchema(accessControlServiceMethods.ByName("CheckAccess")),
			connect.WithClientOptions(opts...),
		),
	}
}

// accessControlServiceClient implements AccessControlServiceClient.
type accessControlServiceClient struct {
	checkAccess *connect.Client[v1.CheckAccessRequest, v1.CheckAccessResponse]
}

// CheckAccess calls accesscontrol.v1.AccessControlService.CheckAccess.
func (c *accessControlServiceClient) CheckAccess(ctx context.Context, req *connect.Request[v1.CheckAccessRequest]) (*connect.Response[v1.CheckAccessResponse], error) {
	return c.checkAccess.CallUnary(ctx, req)
}

// AccessControlServiceHandler is an implementation of the accesscontrol.v1.AccessControlService
// service.
type AccessControlServiceHandler interface {
	// CheckAccess decides whether a requesting process may resolve the
	// secrets matched by the query. Called for every GetSecrets request.
	CheckAccess(context.Context, *connect.Request[v1.CheckAccessRequest]) (*connect.Response[v1.CheckAccessResponse], error)
}

// NewAccessControlServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewAccessControlServiceHandler(svc AccessControlServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	accessControlServiceMethods := v1.File_accesscontrol_v1_api_proto.Services().ByName("AccessControlService").Methods()
	accessControlServiceCheckAccessHandler := connect.NewUnaryHandler(
		AccessControlServiceCheckAccessProcedure,
		svc.CheckAccess,
		connect.WithSchema(accessControlServiceMethods.ByName("CheckAccess")),
		connect.WithHandlerOptions(opts...),
	)
	return "/accesscontrol.v1.AccessControlService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case AccessControlServiceCheckAccessProcedure:
			accessControlServiceCheckAccessHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedAccessControlServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedAccessControlServiceHandler struct{}

func (UnimplementedAccessControlServiceHandler) CheckAccess(context.Context, *connect.Request[v1.CheckAccessRequest]) (*connect.Response[v1.CheckAccessResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("accesscontrol.v1.AccessControlService.CheckAccess is not implemented"))
}
