---
blocked:
  modules:
    - github.com/docker/secrets-engine/engine:
        reason: "Forbidden dependency"
    - github.com/docker/secrets-engine/plugin:
        reason: "Forbidden dependency"
    - github.com/docker/secrets-engine/store:
        reason: "Forbidden dependency"