#!/bin/bash

# 1. Check relevant binaries available
# 2. Creates the necessary files for the keyring daemon
# 3. Starts the dbus daemon
# 4. Sets the `DBUS_SESSION_BUS_ADDRESS` environment variable
# 5. Starts the keyring
# 6. Waits for the keyring to be active by polling dbus over `gdbus`
# 7. Check if the registered `org.freedesktop.secrets` backend matches what we expect.

set -euxo pipefail

if test -z $(command -v gnome-keyring-daemon); then
    echo "gnome-keyring-daemon is not installed"
    exit 1
fi

if test -z $(command -v dbus-daemon); then
    echo "dbus-daemon is not installed"
    exit 1
fi

if ! test -d ~/.local/share/keyrings; then 
    mkdir -p ~/.local/share/keyrings
fi

if ! test -e ~/.local/share/keyrings/login.keyring; then
    touch ~/.local/share/keyrings/login.keyring
fi

# create fake passwordless 'login' keyring
echo '[keyring]
display-name=login
ctime=1750965549
mtime=0
lock-on-idle=false
lock-after=false' > ~/.local/share/keyrings/login.keyring

# Start D-Bus session (dbus must be installed)
export DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --session --print-address --fork)

gnome-keyring-daemon --start --components=secrets

# Wait up to 5 seconds for org.freedesktop.secrets to appear on D-Bus
timeout=5000
interval=100
elapsed=0

while ! gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetNameOwner \
  org.freedesktop.secrets >/dev/null 2>&1; do 

    sleep 0.1
    elapsed=$((elapsed + interval))
    if (( elapsed >= timeout )); then
        echo "❌ Timeout waiting for gnome-keyring-daemon to register org.freedesktop.secrets"
        exit 1
    fi
done

owner=$(gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetNameOwner \
  org.freedesktop.secrets | awk -F"'" '{print $2}')

if test -v $owner; then
    echo "there is no owner of the org.freedesktop.secrets API"
    exit 1
fi

pid=$(gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetConnectionUnixProcessID \
  "$owner" | awk '{print $2}' | tr -d ',)')

if test -v $pid; then
    echo "there is no registered org.freedesktop.secrets daemon"
    exit 1
fi

exe=$(readlink -f /proc/$pid/exe)

if [[ "$exe" == *gnome-keyring-daemon* ]]; then
    echo "dbus org.freedesktop.secrets is using gnome-keyring-daemon"
    go test -v -count=1 ./store/keychain/...
    exit 0
fi

echo "dbus org.freedesktop.secrets is not using gnome-keyring-daemon. Using ${exe}"
exit 1
