#!/bin/bash

# 1. Check relevant binaries available
# 2. Creates the necessary files for the keyring daemon
# 3. Starts the dbus daemon
# 4. Sets the `DBUS_SESSION_BUS_ADDRESS` environment variable
# 5. Starts the keyring
# 6. Waits for the keyring to be active by polling dbus over `gdbus`
# 7. Check if the registered `org.freedesktop.secrets` backend matches what we expect.

set -euxo pipefail

kwalletd=$(command -v kwalletd5 || command -v kwalletd6)

if test -z "$kwalletd"; then
    echo "kwalletd5 or kwalletd6 is not installed"
    exit 1
fi

if test -z $(command -v dbus-daemon); then
    echo "dbus-daemon is not installed"
    exit 1
fi

if ! test -d ~/.local/share/dbus-1/services; then
    mkdir -p ~/.local/share/dbus-1/services
fi

if ! test -e ~/.local/share/dbus-1/services/org.freedesktop.secrets.service; then
    touch ~/.local/share/dbus-1/services/org.freedesktop.secrets.service
fi

echo '[D-BUS Service]
Name=org.freedesktop.secrets
Exec=${kwalletd}' > ~/.local/share/dbus-1/services/org.freedesktop.secrets.service


if ! test -d ~/.local/share/kwalletd; then
    mkdir -p ~/.local/share/kwalletd
fi

if ! test -d ~/.config; then
    mkdir ~/.config
fi

echo '[Wallet]
First Use=false
Default Wallet=kwallet' > ~/.config/kwalletrc

echo '[Wallet]
Version=1' > ~/.local/share/kwalletd/kwallet.kwl

export QT_QPA_PLATFORM=minimal

# Start D-Bus session (dbus must be installed)
export DBUS_SESSION_BUS_ADDRESS=$(dbus-daemon --session --print-address --fork)

"$kwalletd" &

# Wait up to 5 seconds for org.freedesktop.secrets to appear on D-Bus
timeout=5000
interval=100
elapsed=0

while ! gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetNameOwner \
  org.freedesktop.secrets >/dev/null 2>&1; do 

    sleep 0.1
    elapsed=$((elapsed + interval))
    if (( elapsed >= timeout )); then
        echo "❌ Timeout waiting for kwalletd to register org.freedesktop.secrets"
        exit 1
    fi
done

owner=$(gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetNameOwner \
  org.freedesktop.secrets | awk -F"'" '{print $2}')

if test -v $owner; then
    echo "there is no owner of the org.freedesktop.secrets API"
    exit 1
fi

pid=$(gdbus call --session \
  --dest org.freedesktop.DBus \
  --object-path /org/freedesktop/DBus \
  --method org.freedesktop.DBus.GetConnectionUnixProcessID \
  "$owner" | awk '{print $2}' | tr -d ',)')

if test -v $pid; then
    echo "there is no registered org.freedesktop.secrets daemon"
    exit 1
fi

exe=$(readlink -f /proc/$pid/exe)

# ksecretd which is part of kwalletd6
# kwalletd5 is part of kwalletd5
if [[ "$exe" == "/usr/bin/ksecretd" || "$exe" == "/usr/bin/kwalletd5" ]]; then
    echo "dbus org.freedesktop.secrets is using ${exe}"
    go test -v -count=1 ./store/keychain/...
    exit 0
fi

echo "dbus org.freedesktop.secrets is not using kwalletd5 or kwalletd6. Using: ${exe}"
exit 1
