// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: plugins/v1/api.proto

package pluginsv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/docker/secrets-engine/x/api/plugins/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PluginManagementServiceName is the fully-qualified name of the PluginManagementService service.
	PluginManagementServiceName = "plugins.v1.PluginManagementService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PluginManagementServiceListPluginsProcedure is the fully-qualified name of the
	// PluginManagementService's ListPlugins RPC.
	PluginManagementServiceListPluginsProcedure = "/plugins.v1.PluginManagementService/ListPlugins"
	// PluginManagementServiceEnablePluginProcedure is the fully-qualified name of the
	// PluginManagementService's EnablePlugin RPC.
	PluginManagementServiceEnablePluginProcedure = "/plugins.v1.PluginManagementService/EnablePlugin"
	// PluginManagementServiceDisablePluginProcedure is the fully-qualified name of the
	// PluginManagementService's DisablePlugin RPC.
	PluginManagementServiceDisablePluginProcedure = "/plugins.v1.PluginManagementService/DisablePlugin"
)

// PluginManagementServiceClient is a client for the plugins.v1.PluginManagementService service.
type PluginManagementServiceClient interface {
	// ListPlugins returns all plugins registered with the engine.
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error)
	// EnablePlugin enables a plugin by name.
	EnablePlugin(context.Context, *connect.Request[v1.EnablePluginRequest]) (*connect.Response[v1.EnablePluginResponse], error)
	// DisablePlugin disables a plugin by name.
	DisablePlugin(context.Context, *connect.Request[v1.DisablePluginRequest]) (*connect.Response[v1.DisablePluginResponse], error)
}

// NewPluginManagementServiceClient constructs a client for the plugins.v1.PluginManagementService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginManagementServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginManagementServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginManagementServiceMethods := v1.File_plugins_v1_api_proto.Services().ByName("PluginManagementService").Methods()
	return &pluginManagementServiceClient{
		listPlugins: connect.NewClient[v1.ListPluginsRequest, v1.ListPluginsResponse](
			httpClient,
			baseURL+PluginManagementServiceListPluginsProcedure,
			connect.WithSchema(pluginManagementServiceMethods.ByName("ListPlugins")),
			connect.WithClientOptions(opts...),
		),
		enablePlugin: connect.NewClient[v1.EnablePluginRequest, v1.EnablePluginResponse](
			httpClient,
			baseURL+PluginManagementServiceEnablePluginProcedure,
			connect.WithSchema(pluginManagementServiceMethods.ByName("EnablePlugin")),
			connect.WithClientOptions(opts...),
		),
		disablePlugin: connect.NewClient[v1.DisablePluginRequest, v1.DisablePluginResponse](
			httpClient,
			baseURL+PluginManagementServiceDisablePluginProcedure,
			connect.WithSchema(pluginManagementServiceMethods.ByName("DisablePlugin")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginManagementServiceClient implements PluginManagementServiceClient.
type pluginManagementServiceClient struct {
	listPlugins   *connect.Client[v1.ListPluginsRequest, v1.ListPluginsResponse]
	enablePlugin  *connect.Client[v1.EnablePluginRequest, v1.EnablePluginResponse]
	disablePlugin *connect.Client[v1.DisablePluginRequest, v1.DisablePluginResponse]
}

// ListPlugins calls plugins.v1.PluginManagementService.ListPlugins.
func (c *pluginManagementServiceClient) ListPlugins(ctx context.Context, req *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error) {
	return c.listPlugins.CallUnary(ctx, req)
}

// EnablePlugin calls plugins.v1.PluginManagementService.EnablePlugin.
func (c *pluginManagementServiceClient) EnablePlugin(ctx context.Context, req *connect.Request[v1.EnablePluginRequest]) (*connect.Response[v1.EnablePluginResponse], error) {
	return c.enablePlugin.CallUnary(ctx, req)
}

// DisablePlugin calls plugins.v1.PluginManagementService.DisablePlugin.
func (c *pluginManagementServiceClient) DisablePlugin(ctx context.Context, req *connect.Request[v1.DisablePluginRequest]) (*connect.Response[v1.DisablePluginResponse], error) {
	return c.disablePlugin.CallUnary(ctx, req)
}

// PluginManagementServiceHandler is an implementation of the plugins.v1.PluginManagementService
// service.
type PluginManagementServiceHandler interface {
	// ListPlugins returns all plugins registered with the engine.
	ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error)
	// EnablePlugin enables a plugin by name.
	EnablePlugin(context.Context, *connect.Request[v1.EnablePluginRequest]) (*connect.Response[v1.EnablePluginResponse], error)
	// DisablePlugin disables a plugin by name.
	DisablePlugin(context.Context, *connect.Request[v1.DisablePluginRequest]) (*connect.Response[v1.DisablePluginResponse], error)
}

// NewPluginManagementServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginManagementServiceHandler(svc PluginManagementServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginManagementServiceMethods := v1.File_plugins_v1_api_proto.Services().ByName("PluginManagementService").Methods()
	pluginManagementServiceListPluginsHandler := connect.NewUnaryHandler(
		PluginManagementServiceListPluginsProcedure,
		svc.ListPlugins,
		connect.WithSchema(pluginManagementServiceMethods.ByName("ListPlugins")),
		connect.WithHandlerOptions(opts...),
	)
	pluginManagementServiceEnablePluginHandler := connect.NewUnaryHandler(
		PluginManagementServiceEnablePluginProcedure,
		svc.EnablePlugin,
		connect.WithSchema(pluginManagementServiceMethods.ByName("EnablePlugin")),
		connect.WithHandlerOptions(opts...),
	)
	pluginManagementServiceDisablePluginHandler := connect.NewUnaryHandler(
		PluginManagementServiceDisablePluginProcedure,
		svc.DisablePlugin,
		connect.WithSchema(pluginManagementServiceMethods.ByName("DisablePlugin")),
		connect.WithHandlerOptions(opts...),
	)
	return "/plugins.v1.PluginManagementService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginManagementServiceListPluginsProcedure:
			pluginManagementServiceListPluginsHandler.ServeHTTP(w, r)
		case PluginManagementServiceEnablePluginProcedure:
			pluginManagementServiceEnablePluginHandler.ServeHTTP(w, r)
		case PluginManagementServiceDisablePluginProcedure:
			pluginManagementServiceDisablePluginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginManagementServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginManagementServiceHandler struct{}

func (UnimplementedPluginManagementServiceHandler) ListPlugins(context.Context, *connect.Request[v1.ListPluginsRequest]) (*connect.Response[v1.ListPluginsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plugins.v1.PluginManagementService.ListPlugins is not implemented"))
}

func (UnimplementedPluginManagementServiceHandler) EnablePlugin(context.Context, *connect.Request[v1.EnablePluginRequest]) (*connect.Response[v1.EnablePluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plugins.v1.PluginManagementService.EnablePlugin is not implemented"))
}

func (UnimplementedPluginManagementServiceHandler) DisablePlugin(context.Context, *connect.Request[v1.DisablePluginRequest]) (*connect.Response[v1.DisablePluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("plugins.v1.PluginManagementService.DisablePlugin is not implemented"))
}
