// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: resolver/v1/api.proto

package resolverv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPluginRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PluginName  *string                `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName"`
	xxx_hidden_PluginIdx   *string                `protobuf:"bytes,2,opt,name=plugin_idx,json=pluginIdx"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RegisterPluginRequest) GetPluginName() string {
	if x != nil {
		if x.xxx_hidden_PluginName != nil {
			return *x.xxx_hidden_PluginName
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) GetPluginIdx() string {
	if x != nil {
		if x.xxx_hidden_PluginIdx != nil {
			return *x.xxx_hidden_PluginIdx
		}
		return ""
	}
	return ""
}

func (x *RegisterPluginRequest) SetPluginName(v string) {
	x.xxx_hidden_PluginName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *RegisterPluginRequest) SetPluginIdx(v string) {
	x.xxx_hidden_PluginIdx = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *RegisterPluginRequest) HasPluginName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RegisterPluginRequest) HasPluginIdx() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RegisterPluginRequest) ClearPluginName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_PluginName = nil
}

func (x *RegisterPluginRequest) ClearPluginIdx() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_PluginIdx = nil
}

type RegisterPluginRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Name of the plugin to register.
	PluginName *string
	// Plugin invocation index. Plugins are called in ascending index order.
	PluginIdx *string
}

func (b0 RegisterPluginRequest_builder) Build() *RegisterPluginRequest {
	m0 := &RegisterPluginRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.PluginName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_PluginName = b.PluginName
	}
	if b.PluginIdx != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_PluginIdx = b.PluginIdx
	}
	return m0
}

type RegisterPluginResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type RegisterPluginResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 RegisterPluginResponse_builder) Build() *RegisterPluginResponse {
	m0 := &RegisterPluginResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ConfigureRequest struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Config              *string                `protobuf:"bytes,1,opt,name=config"`
	xxx_hidden_EngineName          *string                `protobuf:"bytes,2,opt,name=engine_name,json=engineName"`
	xxx_hidden_EngineVersion       *string                `protobuf:"bytes,3,opt,name=engine_version,json=engineVersion"`
	xxx_hidden_RegistrationTimeout int64                  `protobuf:"varint,4,opt,name=registration_timeout,json=registrationTimeout"`
	xxx_hidden_RequestTimeout      int64                  `protobuf:"varint,5,opt,name=request_timeout,json=requestTimeout"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *ConfigureRequest) Reset() {
	*x = ConfigureRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureRequest) ProtoMessage() {}

func (x *ConfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ConfigureRequest) GetConfig() string {
	if x != nil {
		if x.xxx_hidden_Config != nil {
			return *x.xxx_hidden_Config
		}
		return ""
	}
	return ""
}

func (x *ConfigureRequest) GetEngineName() string {
	if x != nil {
		if x.xxx_hidden_EngineName != nil {
			return *x.xxx_hidden_EngineName
		}
		return ""
	}
	return ""
}

func (x *ConfigureRequest) GetEngineVersion() string {
	if x != nil {
		if x.xxx_hidden_EngineVersion != nil {
			return *x.xxx_hidden_EngineVersion
		}
		return ""
	}
	return ""
}

func (x *ConfigureRequest) GetRegistrationTimeout() int64 {
	if x != nil {
		return x.xxx_hidden_RegistrationTimeout
	}
	return 0
}

func (x *ConfigureRequest) GetRequestTimeout() int64 {
	if x != nil {
		return x.xxx_hidden_RequestTimeout
	}
	return 0
}

func (x *ConfigureRequest) SetConfig(v string) {
	x.xxx_hidden_Config = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *ConfigureRequest) SetEngineName(v string) {
	x.xxx_hidden_EngineName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *ConfigureRequest) SetEngineVersion(v string) {
	x.xxx_hidden_EngineVersion = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *ConfigureRequest) SetRegistrationTimeout(v int64) {
	x.xxx_hidden_RegistrationTimeout = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *ConfigureRequest) SetRequestTimeout(v int64) {
	x.xxx_hidden_RequestTimeout = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *ConfigureRequest) HasConfig() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ConfigureRequest) HasEngineName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *ConfigureRequest) HasEngineVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *ConfigureRequest) HasRegistrationTimeout() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *ConfigureRequest) HasRequestTimeout() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *ConfigureRequest) ClearConfig() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Config = nil
}

func (x *ConfigureRequest) ClearEngineName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_EngineName = nil
}

func (x *ConfigureRequest) ClearEngineVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_EngineVersion = nil
}

func (x *ConfigureRequest) ClearRegistrationTimeout() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RegistrationTimeout = 0
}

func (x *ConfigureRequest) ClearRequestTimeout() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_RequestTimeout = 0
}

type ConfigureRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Any plugin-specific data, if present among the engine configuration.
	Config *string
	// Name of the runtime engine is running in.
	EngineName *string
	// Version of the runtime engine is running in.
	EngineVersion *string
	// Configured registration timeout in milliseconds.
	RegistrationTimeout *int64
	// Configured request processing timeout in milliseconds.
	RequestTimeout *int64
}

func (b0 ConfigureRequest_builder) Build() *ConfigureRequest {
	m0 := &ConfigureRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Config != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Config = b.Config
	}
	if b.EngineName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_EngineName = b.EngineName
	}
	if b.EngineVersion != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_EngineVersion = b.EngineVersion
	}
	if b.RegistrationTimeout != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_RegistrationTimeout = *b.RegistrationTimeout
	}
	if b.RequestTimeout != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_RequestTimeout = *b.RequestTimeout
	}
	return m0
}

type ConfigureResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigureResponse) Reset() {
	*x = ConfigureResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigureResponse) ProtoMessage() {}

func (x *ConfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ConfigureResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ConfigureResponse_builder) Build() *ConfigureResponse {
	m0 := &ConfigureResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownRequest_builder) Build() *ShutdownRequest {
	m0 := &ShutdownRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_resolver_v1_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_resolver_v1_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ShutdownResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ShutdownResponse_builder) Build() *ShutdownResponse {
	m0 := &ShutdownResponse{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_resolver_v1_api_proto protoreflect.FileDescriptor

const file_resolver_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x15resolver/v1/api.proto\x12\vresolver.v1\"W\n" +
	"\x15RegisterPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x1d\n" +
	"\n" +
	"plugin_idx\x18\x02 \x01(\tR\tpluginIdx\"\x18\n" +
	"\x16RegisterPluginResponse\"\xce\x01\n" +
	"\x10ConfigureRequest\x12\x16\n" +
	"\x06config\x18\x01 \x01(\tR\x06config\x12\x1f\n" +
	"\vengine_name\x18\x02 \x01(\tR\n" +
	"engineName\x12%\n" +
	"\x0eengine_version\x18\x03 \x01(\tR\rengineVersion\x121\n" +
	"\x14registration_timeout\x18\x04 \x01(\x03R\x13registrationTimeout\x12'\n" +
	"\x0frequest_timeout\x18\x05 \x01(\x03R\x0erequestTimeout\"\x13\n" +
	"\x11ConfigureResponse\"\x11\n" +
	"\x0fShutdownRequest\"\x12\n" +
	"\x10ShutdownResponse2j\n" +
	"\rEngineService\x12Y\n" +
	"\x0eRegisterPlugin\x12\".resolver.v1.RegisterPluginRequest\x1a#.resolver.v1.RegisterPluginResponse2\xa4\x01\n" +
	"\rPluginService\x12J\n" +
	"\tConfigure\x12\x1d.resolver.v1.ConfigureRequest\x1a\x1e.resolver.v1.ConfigureResponse\x12G\n" +
	"\bShutdown\x12\x1c.resolver.v1.ShutdownRequest\x1a\x1d.resolver.v1.ShutdownResponseB\xa9\x01\n" +
	"\x0fcom.resolver.v1B\bApiProtoP\x01Z?github.com/docker/secrets-engine/pkg/api/resolver/v1;resolverv1\xa2\x02\x03RXX\xaa\x02\vResolver.V1\xca\x02\vResolver\\V1\xe2\x02\x17Resolver\\V1\\GPBMetadata\xea\x02\fResolver::V1b\beditionsp\xe8\a"

var file_resolver_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_resolver_v1_api_proto_goTypes = []any{
	(*RegisterPluginRequest)(nil),  // 0: resolver.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil), // 1: resolver.v1.RegisterPluginResponse
	(*ConfigureRequest)(nil),       // 2: resolver.v1.ConfigureRequest
	(*ConfigureResponse)(nil),      // 3: resolver.v1.ConfigureResponse
	(*ShutdownRequest)(nil),        // 4: resolver.v1.ShutdownRequest
	(*ShutdownResponse)(nil),       // 5: resolver.v1.ShutdownResponse
}
var file_resolver_v1_api_proto_depIdxs = []int32{
	0, // 0: resolver.v1.EngineService.RegisterPlugin:input_type -> resolver.v1.RegisterPluginRequest
	2, // 1: resolver.v1.PluginService.Configure:input_type -> resolver.v1.ConfigureRequest
	4, // 2: resolver.v1.PluginService.Shutdown:input_type -> resolver.v1.ShutdownRequest
	1, // 3: resolver.v1.EngineService.RegisterPlugin:output_type -> resolver.v1.RegisterPluginResponse
	3, // 4: resolver.v1.PluginService.Configure:output_type -> resolver.v1.ConfigureResponse
	5, // 5: resolver.v1.PluginService.Shutdown:output_type -> resolver.v1.ShutdownResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_resolver_v1_api_proto_init() }
func file_resolver_v1_api_proto_init() {
	if File_resolver_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_resolver_v1_api_proto_rawDesc), len(file_resolver_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_resolver_v1_api_proto_goTypes,
		DependencyIndexes: file_resolver_v1_api_proto_depIdxs,
		MessageInfos:      file_resolver_v1_api_proto_msgTypes,
	}.Build()
	File_resolver_v1_api_proto = out.File
	file_resolver_v1_api_proto_goTypes = nil
	file_resolver_v1_api_proto_depIdxs = nil
}
