// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        (unknown)
// source: health/v1/api.proto

package healthv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetVersionRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVersionRequest) Reset() {
	*x = GetVersionRequest{}
	mi := &file_health_v1_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionRequest) ProtoMessage() {}

func (x *GetVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type GetVersionRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 GetVersionRequest_builder) Build() *GetVersionRequest {
	m0 := &GetVersionRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type GetVersionResponse struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Version     *string                `protobuf:"bytes,1,opt,name=version"`
	xxx_hidden_Date        *string                `protobuf:"bytes,2,opt,name=date"`
	xxx_hidden_CommitHash  *string                `protobuf:"bytes,3,opt,name=commit_hash,json=commitHash"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GetVersionResponse) Reset() {
	*x = GetVersionResponse{}
	mi := &file_health_v1_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVersionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVersionResponse) ProtoMessage() {}

func (x *GetVersionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_health_v1_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetVersionResponse) GetVersion() string {
	if x != nil {
		if x.xxx_hidden_Version != nil {
			return *x.xxx_hidden_Version
		}
		return ""
	}
	return ""
}

func (x *GetVersionResponse) GetDate() string {
	if x != nil {
		if x.xxx_hidden_Date != nil {
			return *x.xxx_hidden_Date
		}
		return ""
	}
	return ""
}

func (x *GetVersionResponse) GetCommitHash() string {
	if x != nil {
		if x.xxx_hidden_CommitHash != nil {
			return *x.xxx_hidden_CommitHash
		}
		return ""
	}
	return ""
}

func (x *GetVersionResponse) SetVersion(v string) {
	x.xxx_hidden_Version = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *GetVersionResponse) SetDate(v string) {
	x.xxx_hidden_Date = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *GetVersionResponse) SetCommitHash(v string) {
	x.xxx_hidden_CommitHash = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *GetVersionResponse) HasVersion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *GetVersionResponse) HasDate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *GetVersionResponse) HasCommitHash() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *GetVersionResponse) ClearVersion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Version = nil
}

func (x *GetVersionResponse) ClearDate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Date = nil
}

func (x *GetVersionResponse) ClearCommitHash() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CommitHash = nil
}

type GetVersionResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Version    *string
	Date       *string
	CommitHash *string
}

func (b0 GetVersionResponse_builder) Build() *GetVersionResponse {
	m0 := &GetVersionResponse{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Version != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Version = b.Version
	}
	if b.Date != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Date = b.Date
	}
	if b.CommitHash != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_CommitHash = b.CommitHash
	}
	return m0
}

var File_health_v1_api_proto protoreflect.FileDescriptor

const file_health_v1_api_proto_rawDesc = "" +
	"\n" +
	"\x13health/v1/api.proto\x12\thealth.v1\"\x13\n" +
	"\x11GetVersionRequest\"c\n" +
	"\x12GetVersionResponse\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x1f\n" +
	"\vcommit_hash\x18\x03 \x01(\tR\n" +
	"commitHash2[\n" +
	"\x0eVersionService\x12I\n" +
	"\n" +
	"GetVersion\x12\x1c.health.v1.GetVersionRequest\x1a\x1d.health.v1.GetVersionResponseB\x99\x01\n" +
	"\rcom.health.v1B\bApiProtoP\x01Z9github.com/docker/secrets-engine/x/api/health/v1;healthv1\xa2\x02\x03HXX\xaa\x02\tHealth.V1\xca\x02\tHealth\\V1\xe2\x02\x15Health\\V1\\GPBMetadata\xea\x02\n" +
	"Health::V1b\beditionsp\xe8\a"

var file_health_v1_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_health_v1_api_proto_goTypes = []any{
	(*GetVersionRequest)(nil),  // 0: health.v1.GetVersionRequest
	(*GetVersionResponse)(nil), // 1: health.v1.GetVersionResponse
}
var file_health_v1_api_proto_depIdxs = []int32{
	0, // 0: health.v1.VersionService.GetVersion:input_type -> health.v1.GetVersionRequest
	1, // 1: health.v1.VersionService.GetVersion:output_type -> health.v1.GetVersionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_health_v1_api_proto_init() }
func file_health_v1_api_proto_init() {
	if File_health_v1_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_health_v1_api_proto_rawDesc), len(file_health_v1_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_health_v1_api_proto_goTypes,
		DependencyIndexes: file_health_v1_api_proto_depIdxs,
		MessageInfos:      file_health_v1_api_proto_msgTypes,
	}.Build()
	File_health_v1_api_proto = out.File
	file_health_v1_api_proto_goTypes = nil
	file_health_v1_api_proto_depIdxs = nil
}
