// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: resolver/v1/api.proto

package resolverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/docker/secrets-engine/pkg/api/resolver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EngineName is the fully-qualified name of the Engine service.
	EngineName = "secrets_engine.api.v1.Engine"
	// PluginName is the fully-qualified name of the Plugin service.
	PluginName = "secrets_engine.api.v1.Plugin"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EngineRegisterPluginProcedure is the fully-qualified name of the Engine's RegisterPlugin RPC.
	EngineRegisterPluginProcedure = "/secrets_engine.api.v1.Engine/RegisterPlugin"
	// PluginConfigureProcedure is the fully-qualified name of the Plugin's Configure RPC.
	PluginConfigureProcedure = "/secrets_engine.api.v1.Plugin/Configure"
	// PluginShutdownProcedure is the fully-qualified name of the Plugin's Shutdown RPC.
	PluginShutdownProcedure = "/secrets_engine.api.v1.Plugin/Shutdown"
)

// EngineClient is a client for the secrets_engine.api.v1.Engine service.
type EngineClient interface {
	// RegisterPlugin registers the plugin with the engine.
	RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.Empty], error)
}

// NewEngineClient constructs a client for the secrets_engine.api.v1.Engine service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEngineClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EngineClient {
	baseURL = strings.TrimRight(baseURL, "/")
	engineMethods := v1.File_resolver_v1_api_proto.Services().ByName("Engine").Methods()
	return &engineClient{
		registerPlugin: connect.NewClient[v1.RegisterPluginRequest, v1.Empty](
			httpClient,
			baseURL+EngineRegisterPluginProcedure,
			connect.WithSchema(engineMethods.ByName("RegisterPlugin")),
			connect.WithClientOptions(opts...),
		),
	}
}

// engineClient implements EngineClient.
type engineClient struct {
	registerPlugin *connect.Client[v1.RegisterPluginRequest, v1.Empty]
}

// RegisterPlugin calls secrets_engine.api.v1.Engine.RegisterPlugin.
func (c *engineClient) RegisterPlugin(ctx context.Context, req *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.Empty], error) {
	return c.registerPlugin.CallUnary(ctx, req)
}

// EngineHandler is an implementation of the secrets_engine.api.v1.Engine service.
type EngineHandler interface {
	// RegisterPlugin registers the plugin with the engine.
	RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.Empty], error)
}

// NewEngineHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEngineHandler(svc EngineHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	engineMethods := v1.File_resolver_v1_api_proto.Services().ByName("Engine").Methods()
	engineRegisterPluginHandler := connect.NewUnaryHandler(
		EngineRegisterPluginProcedure,
		svc.RegisterPlugin,
		connect.WithSchema(engineMethods.ByName("RegisterPlugin")),
		connect.WithHandlerOptions(opts...),
	)
	return "/secrets_engine.api.v1.Engine/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EngineRegisterPluginProcedure:
			engineRegisterPluginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEngineHandler returns CodeUnimplemented from all methods.
type UnimplementedEngineHandler struct{}

func (UnimplementedEngineHandler) RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("secrets_engine.api.v1.Engine.RegisterPlugin is not implemented"))
}

// PluginClient is a client for the secrets_engine.api.v1.Plugin service.
type PluginClient interface {
	// Configure the plugin and get its event subscription.
	Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.Empty], error)
	// Shutdown a plugin (let it know the runtime is going down).
	Shutdown(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error)
}

// NewPluginClient constructs a client for the secrets_engine.api.v1.Plugin service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginMethods := v1.File_resolver_v1_api_proto.Services().ByName("Plugin").Methods()
	return &pluginClient{
		configure: connect.NewClient[v1.ConfigureRequest, v1.Empty](
			httpClient,
			baseURL+PluginConfigureProcedure,
			connect.WithSchema(pluginMethods.ByName("Configure")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[v1.Empty, v1.Empty](
			httpClient,
			baseURL+PluginShutdownProcedure,
			connect.WithSchema(pluginMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginClient implements PluginClient.
type pluginClient struct {
	configure *connect.Client[v1.ConfigureRequest, v1.Empty]
	shutdown  *connect.Client[v1.Empty, v1.Empty]
}

// Configure calls secrets_engine.api.v1.Plugin.Configure.
func (c *pluginClient) Configure(ctx context.Context, req *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.Empty], error) {
	return c.configure.CallUnary(ctx, req)
}

// Shutdown calls secrets_engine.api.v1.Plugin.Shutdown.
func (c *pluginClient) Shutdown(ctx context.Context, req *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// PluginHandler is an implementation of the secrets_engine.api.v1.Plugin service.
type PluginHandler interface {
	// Configure the plugin and get its event subscription.
	Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.Empty], error)
	// Shutdown a plugin (let it know the runtime is going down).
	Shutdown(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error)
}

// NewPluginHandler builds an HTTP handler from the service implementation. It returns the path on
// which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginHandler(svc PluginHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginMethods := v1.File_resolver_v1_api_proto.Services().ByName("Plugin").Methods()
	pluginConfigureHandler := connect.NewUnaryHandler(
		PluginConfigureProcedure,
		svc.Configure,
		connect.WithSchema(pluginMethods.ByName("Configure")),
		connect.WithHandlerOptions(opts...),
	)
	pluginShutdownHandler := connect.NewUnaryHandler(
		PluginShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(pluginMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	return "/secrets_engine.api.v1.Plugin/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginConfigureProcedure:
			pluginConfigureHandler.ServeHTTP(w, r)
		case PluginShutdownProcedure:
			pluginShutdownHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginHandler struct{}

func (UnimplementedPluginHandler) Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("secrets_engine.api.v1.Plugin.Configure is not implemented"))
}

func (UnimplementedPluginHandler) Shutdown(context.Context, *connect.Request[v1.Empty]) (*connect.Response[v1.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("secrets_engine.api.v1.Plugin.Shutdown is not implemented"))
}
