// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: resolver/v1/api.proto

package resolverv1connect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/docker/secrets-engine/pkg/api/resolver/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// EngineServiceName is the fully-qualified name of the EngineService service.
	EngineServiceName = "resolver.v1.EngineService"
	// PluginServiceName is the fully-qualified name of the PluginService service.
	PluginServiceName = "resolver.v1.PluginService"
	// ResolverServiceName is the fully-qualified name of the ResolverService service.
	ResolverServiceName = "resolver.v1.ResolverService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// EngineServiceRegisterPluginProcedure is the fully-qualified name of the EngineService's
	// RegisterPlugin RPC.
	EngineServiceRegisterPluginProcedure = "/resolver.v1.EngineService/RegisterPlugin"
	// PluginServiceConfigureProcedure is the fully-qualified name of the PluginService's Configure RPC.
	PluginServiceConfigureProcedure = "/resolver.v1.PluginService/Configure"
	// PluginServiceShutdownProcedure is the fully-qualified name of the PluginService's Shutdown RPC.
	PluginServiceShutdownProcedure = "/resolver.v1.PluginService/Shutdown"
	// ResolverServiceGetSecretProcedure is the fully-qualified name of the ResolverService's GetSecret
	// RPC.
	ResolverServiceGetSecretProcedure = "/resolver.v1.ResolverService/GetSecret"
)

// EngineServiceClient is a client for the resolver.v1.EngineService service.
type EngineServiceClient interface {
	// RegisterPlugin registers the plugin with the engine.
	RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.RegisterPluginResponse], error)
}

// NewEngineServiceClient constructs a client for the resolver.v1.EngineService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewEngineServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) EngineServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	engineServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("EngineService").Methods()
	return &engineServiceClient{
		registerPlugin: connect.NewClient[v1.RegisterPluginRequest, v1.RegisterPluginResponse](
			httpClient,
			baseURL+EngineServiceRegisterPluginProcedure,
			connect.WithSchema(engineServiceMethods.ByName("RegisterPlugin")),
			connect.WithClientOptions(opts...),
		),
	}
}

// engineServiceClient implements EngineServiceClient.
type engineServiceClient struct {
	registerPlugin *connect.Client[v1.RegisterPluginRequest, v1.RegisterPluginResponse]
}

// RegisterPlugin calls resolver.v1.EngineService.RegisterPlugin.
func (c *engineServiceClient) RegisterPlugin(ctx context.Context, req *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.RegisterPluginResponse], error) {
	return c.registerPlugin.CallUnary(ctx, req)
}

// EngineServiceHandler is an implementation of the resolver.v1.EngineService service.
type EngineServiceHandler interface {
	// RegisterPlugin registers the plugin with the engine.
	RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.RegisterPluginResponse], error)
}

// NewEngineServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewEngineServiceHandler(svc EngineServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	engineServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("EngineService").Methods()
	engineServiceRegisterPluginHandler := connect.NewUnaryHandler(
		EngineServiceRegisterPluginProcedure,
		svc.RegisterPlugin,
		connect.WithSchema(engineServiceMethods.ByName("RegisterPlugin")),
		connect.WithHandlerOptions(opts...),
	)
	return "/resolver.v1.EngineService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case EngineServiceRegisterPluginProcedure:
			engineServiceRegisterPluginHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedEngineServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedEngineServiceHandler struct{}

func (UnimplementedEngineServiceHandler) RegisterPlugin(context.Context, *connect.Request[v1.RegisterPluginRequest]) (*connect.Response[v1.RegisterPluginResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resolver.v1.EngineService.RegisterPlugin is not implemented"))
}

// PluginServiceClient is a client for the resolver.v1.PluginService service.
type PluginServiceClient interface {
	// Configure the plugin and get its event subscription.
	Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.ConfigureResponse], error)
	// Shutdown a plugin (let it know the runtime is going down).
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
}

// NewPluginServiceClient constructs a client for the resolver.v1.PluginService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPluginServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PluginServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	pluginServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("PluginService").Methods()
	return &pluginServiceClient{
		configure: connect.NewClient[v1.ConfigureRequest, v1.ConfigureResponse](
			httpClient,
			baseURL+PluginServiceConfigureProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("Configure")),
			connect.WithClientOptions(opts...),
		),
		shutdown: connect.NewClient[v1.ShutdownRequest, v1.ShutdownResponse](
			httpClient,
			baseURL+PluginServiceShutdownProcedure,
			connect.WithSchema(pluginServiceMethods.ByName("Shutdown")),
			connect.WithClientOptions(opts...),
		),
	}
}

// pluginServiceClient implements PluginServiceClient.
type pluginServiceClient struct {
	configure *connect.Client[v1.ConfigureRequest, v1.ConfigureResponse]
	shutdown  *connect.Client[v1.ShutdownRequest, v1.ShutdownResponse]
}

// Configure calls resolver.v1.PluginService.Configure.
func (c *pluginServiceClient) Configure(ctx context.Context, req *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.ConfigureResponse], error) {
	return c.configure.CallUnary(ctx, req)
}

// Shutdown calls resolver.v1.PluginService.Shutdown.
func (c *pluginServiceClient) Shutdown(ctx context.Context, req *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return c.shutdown.CallUnary(ctx, req)
}

// PluginServiceHandler is an implementation of the resolver.v1.PluginService service.
type PluginServiceHandler interface {
	// Configure the plugin and get its event subscription.
	Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.ConfigureResponse], error)
	// Shutdown a plugin (let it know the runtime is going down).
	Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error)
}

// NewPluginServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPluginServiceHandler(svc PluginServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	pluginServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("PluginService").Methods()
	pluginServiceConfigureHandler := connect.NewUnaryHandler(
		PluginServiceConfigureProcedure,
		svc.Configure,
		connect.WithSchema(pluginServiceMethods.ByName("Configure")),
		connect.WithHandlerOptions(opts...),
	)
	pluginServiceShutdownHandler := connect.NewUnaryHandler(
		PluginServiceShutdownProcedure,
		svc.Shutdown,
		connect.WithSchema(pluginServiceMethods.ByName("Shutdown")),
		connect.WithHandlerOptions(opts...),
	)
	return "/resolver.v1.PluginService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PluginServiceConfigureProcedure:
			pluginServiceConfigureHandler.ServeHTTP(w, r)
		case PluginServiceShutdownProcedure:
			pluginServiceShutdownHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPluginServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPluginServiceHandler struct{}

func (UnimplementedPluginServiceHandler) Configure(context.Context, *connect.Request[v1.ConfigureRequest]) (*connect.Response[v1.ConfigureResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resolver.v1.PluginService.Configure is not implemented"))
}

func (UnimplementedPluginServiceHandler) Shutdown(context.Context, *connect.Request[v1.ShutdownRequest]) (*connect.Response[v1.ShutdownResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resolver.v1.PluginService.Shutdown is not implemented"))
}

// ResolverServiceClient is a client for the resolver.v1.ResolverService service.
type ResolverServiceClient interface {
	// Resolve a secret by its ID.
	GetSecret(context.Context, *connect.Request[v1.GetSecretRequest]) (*connect.Response[v1.GetSecretResponse], error)
}

// NewResolverServiceClient constructs a client for the resolver.v1.ResolverService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewResolverServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ResolverServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	resolverServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("ResolverService").Methods()
	return &resolverServiceClient{
		getSecret: connect.NewClient[v1.GetSecretRequest, v1.GetSecretResponse](
			httpClient,
			baseURL+ResolverServiceGetSecretProcedure,
			connect.WithSchema(resolverServiceMethods.ByName("GetSecret")),
			connect.WithClientOptions(opts...),
		),
	}
}

// resolverServiceClient implements ResolverServiceClient.
type resolverServiceClient struct {
	getSecret *connect.Client[v1.GetSecretRequest, v1.GetSecretResponse]
}

// GetSecret calls resolver.v1.ResolverService.GetSecret.
func (c *resolverServiceClient) GetSecret(ctx context.Context, req *connect.Request[v1.GetSecretRequest]) (*connect.Response[v1.GetSecretResponse], error) {
	return c.getSecret.CallUnary(ctx, req)
}

// ResolverServiceHandler is an implementation of the resolver.v1.ResolverService service.
type ResolverServiceHandler interface {
	// Resolve a secret by its ID.
	GetSecret(context.Context, *connect.Request[v1.GetSecretRequest]) (*connect.Response[v1.GetSecretResponse], error)
}

// NewResolverServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewResolverServiceHandler(svc ResolverServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	resolverServiceMethods := v1.File_resolver_v1_api_proto.Services().ByName("ResolverService").Methods()
	resolverServiceGetSecretHandler := connect.NewUnaryHandler(
		ResolverServiceGetSecretProcedure,
		svc.GetSecret,
		connect.WithSchema(resolverServiceMethods.ByName("GetSecret")),
		connect.WithHandlerOptions(opts...),
	)
	return "/resolver.v1.ResolverService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ResolverServiceGetSecretProcedure:
			resolverServiceGetSecretHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedResolverServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedResolverServiceHandler struct{}

func (UnimplementedResolverServiceHandler) GetSecret(context.Context, *connect.Request[v1.GetSecretRequest]) (*connect.Response[v1.GetSecretResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("resolver.v1.ResolverService.GetSecret is not implemented"))
}
