name: Go Work Check
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      pull-requests: write
      contents: write
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Setup Go
        uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5
        with:
          go-version-file: go.work
      - name: Check if go work sync/vendor is clean
        run: |-
          go work sync
          go work vendor
          if [[ -n "$(git status --porcelain)" ]]; then
            echo "::error::Go work sync/vendor files need to be updated. Please run 'go work sync' and 'go mod vendor' and commit the changes."
            git status
            git diff
            exit 1
          fi
